<?php

namespace Database\Seeders;

use App\Enums\CatalogRightsClass;
use App\Enums\SupplierOnboardingStatus;
use App\Enums\SupplierProtocol;
use App\Enums\SupplierStrategicRole;
use App\Enums\SupplierType;
use App\Models\Supplier;
use Illuminate\Database\Seeder;

/**
 * Seeds the qualified supplier universe from the 2026-09-06 research dossiers as
 * commercial prospects.
 *
 * Every record here is public-evidence qualification, not a negotiated term. No
 * supplier is activated, none has credentials, and capability flags are only set
 * where the research explicitly documents the capability. A null capability means
 * "not established yet" and must be answered by the supplier, not guessed.
 *
 * The seeder is additive: an existing supplier code is never overwritten, so
 * operator edits and real commercial answers always win over research defaults.
 *
 * Sources:
 *   docs/automotive_dropshipping_supplier_research_eu_us_2026-09-06.md
 *   docs/automotive_4x4_offroad_supplier_strategy_2026-09-06.md
 */
class SupplierProspectSeeder extends Seeder
{
    public function run(): void
    {
        foreach ([...$this->europeanSuppliers(), ...$this->unitedStatesSuppliers()] as $prospect) {
            $this->seed($prospect);
        }
    }

    /** @param array<string, mixed> $prospect */
    private function seed(array $prospect): void
    {
        $sources = $prospect['sources'] ?? [];
        $unresolved = $prospect['unresolved'] ?? [];
        unset($prospect['sources'], $prospect['unresolved']);

        Supplier::query()->firstOrCreate(
            ['code' => $prospect['code']],
            [
                ...$prospect,
                'is_active' => false,
                'onboarding_status' => $prospect['onboarding_status'] ?? SupplierOnboardingStatus::NotStarted,
                'data_rights_class' => CatalogRightsClass::UnknownPendingReview,
                'allow_internal_data' => true,
                'allow_ecommerce_data' => false,
                'allow_derived_data' => false,
                'allow_api_redistribution' => false,
                'credentials' => [],
                'field_mapping' => [],
                'settings' => ['profile_status' => 'prospect_awaiting_commercial_qualification'],
                'commercial_profile' => [
                    'research_date' => '2026-09-06',
                    'sources' => $sources,
                    'unresolved' => $unresolved,
                ],
            ],
        );
    }

    /**
     * EU / Europe. Qualification scores from the research dossier §25, integration
     * readiness from §3, off-road fit from the 4x4 strategy §3.
     *
     * @return list<array<string, mixed>>
     */
    private function europeanSuppliers(): array
    {
        return [
            [
                'code' => 'AVEX',
                'name' => 'AVEX',
                'country_code' => 'RO',
                'website' => 'https://avex.ro/',
                'supplier_type' => SupplierType::Distributor,
                'strategic_role' => SupplierStrategicRole::Backbone,
                'protocol' => SupplierProtocol::Xml,
                'default_currency' => 'RON',
                'timezone' => 'Europe/Bucharest',
                'priority' => 10,
                'qualification_score' => 91,
                'readiness_score' => 4,
                'offroad_fit_score' => 95,
                'supports_catalog' => true,
                'supports_prices' => true,
                'supports_stock' => true,
                'return_window_days' => 14,
                'return_freight_payer' => 'reseller',
                'onboarding_notes' => 'Cel mai mic prag de intrare pentru o lansare Romania-first: dropship explicit, feeduri XML/CSV/XLSX actualizate orar, accesorii off-road/ATV/SSV, iluminat, electrice. Retururile dropship B2B sunt acceptate 14 zile pentru marfa nouă/sigilată, transportul retur e plătit de revânzător, iar creditul intră în portofelul AVEX, nu prin transfer bancar. Feed separat pentru produse nou adăugate.',
                'next_action' => 'Deschide cont B2B dropship. Cere tabelul de tarife curier, confirmarea documentelor neutre, endpointul de comandă automată și o mostră de feed XML/XLSX.',
                'sources' => ['https://avex.ro/dropshipping.html', 'https://avex.ro/integrari-api-feeds.html', 'https://avex.ro/politica-de-retur.html'],
                'unresolved' => ['tarif curier exact', 'documente neutre', 'endpoint comandă automată', 'ladder de discount'],
            ],
            [
                'code' => 'KITT',
                'name' => 'KITT Tuning / CarPartsTuning',
                'country_code' => 'RO',
                'website' => 'https://www.carpartstuning.com/',
                'supplier_type' => SupplierType::Distributor,
                'strategic_role' => SupplierStrategicRole::Specialist,
                'protocol' => SupplierProtocol::Xml,
                'default_currency' => 'RON',
                'timezone' => 'Europe/Bucharest',
                'priority' => 20,
                'qualification_score' => 84,
                'readiness_score' => 4,
                'offroad_fit_score' => 92,
                'supports_catalog' => true,
                'supports_prices' => true,
                'supports_stock' => true,
                'onboarding_notes' => 'Cea mai bună diferențiere românească pe produse vehicle-specific: praguri laterale, componente exterioare SUV pentru Land Cruiser, Land Rover și familii similare. ATENȚIE conformitate: unele pagini de produs declară explicit lipsa E-mark / ABE / TÜV. Catalogul NU poate fi ingerat cu road_legal_status implicit legal; SKU-urile intră UNKNOWN sau OFFROAD_ONLY până la documentație verificată.',
                'next_action' => 'Deschide cont B2B. Cere ladder-ul de discount, taxele de dropship, politica de factură neutră, automatizarea comenzii și lista SKU cu documentație de omologare.',
                'sources' => ['https://m.carpartstuning.com/index.php?page=become_b2b'],
                'unresolved' => ['discount ladder', 'taxă dropship', 'factură neutră', 'API/automatizare comandă', 'documente omologare per SKU'],
            ],
            [
                'code' => 'EHORNET',
                'name' => 'eHornet',
                'country_code' => 'BG',
                'website' => 'https://ehornet.eu/partner',
                'supplier_type' => SupplierType::Distributor,
                'strategic_role' => SupplierStrategicRole::Backbone,
                'protocol' => SupplierProtocol::Api,
                'default_currency' => 'EUR',
                'priority' => 30,
                'qualification_score' => 91,
                'readiness_score' => 5,
                'offroad_fit_score' => 88,
                'supports_catalog' => true,
                'supports_prices' => true,
                'supports_stock' => true,
                'onboarding_notes' => 'Cel mai bun gateway regional CEE pentru o operațiune din România: 150k+ SKU, 500+ branduri, 50+ furnizori activi, REST API plus CSV și XML, sincronizare zilnică stoc/preț, dropship / cross-dock / palet în BG, RO, GR și CEE. Onboarding de partener promovat în ~48h.',
                'next_action' => 'Cere pachetul de partener: tarife de livrare în România, politica de retur, documentele neutre, scopul exact al API-ului de comandă/tracking și o mostră de feed.',
                'sources' => ['https://ehornet.eu/partner'],
                'unresolved' => ['tarife RO', 'retururi', 'documente neutre', 'scop API comandă/tracking'],
            ],
            [
                'code' => 'TASY',
                'name' => 'TASY',
                'country_code' => 'CZ',
                'website' => 'https://api.tasy.cz/',
                'supplier_type' => SupplierType::Distributor,
                'strategic_role' => SupplierStrategicRole::Backbone,
                'protocol' => SupplierProtocol::Api,
                'default_currency' => 'EUR',
                'timezone' => 'Europe/Prague',
                'priority' => 40,
                'qualification_score' => 92,
                'readiness_score' => 5,
                'offroad_fit_score' => 87,
                'supports_catalog' => true,
                'supports_prices' => true,
                'supports_stock' => true,
                'supports_order_api' => true,
                'supports_tracking_api' => true,
                'merchant_as_sender' => true,
                'onboarding_notes' => 'Cel mai complet stack public de automatizare găsit în Europa pentru anvelope/jante: API sau FTP XML, catalog complet cu imagini, stoc și prețuri, trimitere electronică a comenzilor, control status/tracking, facturi XML și expediere directă către client cu numele revânzătorului pe etichetă. Candidatul potrivit pentru a valida întâi fluxul comandă + tracking.',
                'next_action' => 'Cere documentația API, credențiale sandbox, tarifele de transport în România, condițiile de retur și aplicabilitatea ramburs transfrontalier.',
                'sources' => ['https://api.tasy.cz/', 'https://www.tasy.cz/en/tyre-distribution/for-suppliers'],
                'unresolved' => ['tarife RO', 'condiții retur', 'ramburs transfrontalier', 'lățimea gamei off-road'],
            ],
            [
                'code' => 'VITIRE',
                'name' => 'ViTire',
                'country_code' => 'PL',
                'website' => 'https://vitire.eu/en/',
                'supplier_type' => SupplierType::Distributor,
                'strategic_role' => SupplierStrategicRole::Specialist,
                'protocol' => SupplierProtocol::Xml,
                'default_currency' => 'EUR',
                'timezone' => 'Europe/Warsaw',
                'priority' => 50,
                'qualification_score' => 82,
                'readiness_score' => 4,
                'offroad_fit_score' => 91,
                'supports_catalog' => true,
                'supports_prices' => true,
                'supports_stock' => true,
                'onboarding_notes' => 'Specialist de anvelope off-road și motorsport, crescut din RacingTires.pl și OffroadTires.pl. Gamă mud/extreme terrain relevantă direct pentru poziționarea 4x4. Anvelopele rămân ancoră de trafic și AOV, nu sursă principală de marjă.',
                'next_action' => 'Deschide cont B2B. Cere mostră XML, tarife de transport anvelope către România, automatizarea comenzii și politica de documente neutre.',
                'sources' => ['https://vitire.eu/en/'],
                'unresolved' => ['automatizare comandă', 'tarife transport RO', 'documente neutre', 'retururi'],
            ],
            [
                'code' => 'FZB_GROSSHANDEL',
                'name' => 'Fahrzeugbeleuchtung-Großhandel.de',
                'country_code' => 'DE',
                'website' => 'https://fahrzeugbeleuchtung-grosshandel.de/',
                'supplier_type' => SupplierType::Wholesaler,
                'strategic_role' => SupplierStrategicRole::Specialist,
                'protocol' => SupplierProtocol::Xml,
                'default_currency' => 'EUR',
                'timezone' => 'Europe/Berlin',
                'priority' => 60,
                'qualification_score' => 86,
                'readiness_score' => 4,
                'offroad_fit_score' => 84,
                'supports_catalog' => true,
                'supports_prices' => true,
                'supports_stock' => true,
                'blind_shipping' => true,
                'neutral_packaging' => true,
                'merchant_as_sender' => true,
                'onboarding_notes' => 'Termenii B2B 2026 fac dropshipping-ul standard și specifică aviz de însoțire neutru cu revânzătorul ca expeditor. Iluminat de vehicul, categorie cu marjă bună. Clasificarea E-mark / uz off-road trebuie făcută per SKU, nu generalizată.',
                'next_action' => 'Înregistrare B2B (verificare manuală a firmei). Cere MOQ exact, costul licenței API, tariful de colet către România și politica de retur.',
                'sources' => ['https://fahrzeugbeleuchtung-grosshandel.de/dropshipping/', 'https://fahrzeugbeleuchtung-grosshandel.de/b2b-registrierung/', 'https://fahrzeugbeleuchtung-grosshandel.de/nutzungsbedingungen/'],
                'unresolved' => ['MOQ exact', 'cost licență API', 'tarif colet RO', 'retururi'],
            ],
            [
                'code' => 'VTVAUTO',
                'name' => 'VTVAuto',
                'country_code' => 'SK',
                'website' => 'https://www.vtvauto.it/home',
                'supplier_type' => SupplierType::Distributor,
                'strategic_role' => SupplierStrategicRole::Specialist,
                'protocol' => SupplierProtocol::Xml,
                'default_currency' => 'EUR',
                'timezone' => 'Europe/Bratislava',
                'priority' => 70,
                'qualification_score' => 79,
                'readiness_score' => 4,
                'offroad_fit_score' => 84,
                'supports_catalog' => true,
                'onboarding_notes' => 'Accesorii 4x4 vehicle-specific: protecție motor/cutie/subansamble, extensii aripi, covorașe, tăvi portbagaj, deflectoare. Produse care se vând pe generație exactă de vehicul, nu ca SKU universal.',
                'next_action' => 'Cere pachetul B2B și o mostră XML. Clarifică livrarea în România, automatizarea comenzii, documentele neutre și regulile de retur.',
                'sources' => ['https://www.vtvauto.it/home'],
                'unresolved' => ['livrare RO', 'automatizare comandă', 'documente neutre', 'retururi'],
            ],
            [
                'code' => 'ALZURA',
                'name' => 'ALZURA / Tyre24',
                'country_code' => 'DE',
                'website' => 'https://tyre24.alzura.com/',
                'supplier_type' => SupplierType::Marketplace,
                'strategic_role' => SupplierStrategicRole::Fallback,
                'protocol' => SupplierProtocol::Api,
                'default_currency' => 'EUR',
                'timezone' => 'Europe/Berlin',
                'priority' => 80,
                'qualification_score' => 87,
                'readiness_score' => 5,
                'offroad_fit_score' => 82,
                'supports_catalog' => true,
                'supports_prices' => true,
                'supports_stock' => true,
                'supports_realtime_stock' => true,
                'supports_order_api' => true,
                'minimum_order_value' => 59.00,
                'terms_currency' => 'EUR',
                'onboarding_notes' => 'Rețea de aprovizionare, nu angrosist clasic: 2.000+ furnizori, 18M+ produse, 15 țări. API real-time plus export CSV până la 24x/zi pe pachetul Pro. distributorList returnează TOȚI furnizorii care dețin un articol, cu preț, termen și disponibilitate proprii. ATENȚIE MODELARE: rămâne UN singur furnizor intern, cu sub-vânzătorul reținut pe ofertă. Cont Basic: minim 59 EUR per furnizor, taxă 3,90 EUR/comandă sub prag; Prime elimină minimul. Pachetele de date sunt plătite. Se deschide ultimul, după ce există trafic real.',
                'next_action' => 'Amână până există volum. Apoi: cont Prime + pachet API, acoperirea furnizorilor pentru România și flagul de dropship per ofertă.',
                'sources' => ['https://tyre24.alzura.com/', 'https://www.alzura-automotive.com/datenpaket', 'https://tyre24.alzura.com/assets/pdf/Article_Export_Technical_Documentation_En.pdf'],
                'unresolved' => ['disponibilitate RO', 'comportament dropship per sub-furnizor', 'cost pachet API'],
            ],
            [
                'code' => 'PARTSMAN',
                'name' => 'Partsman',
                'country_code' => 'PL',
                'website' => 'https://partsman.pl/',
                'supplier_type' => SupplierType::Wholesaler,
                'strategic_role' => SupplierStrategicRole::Backbone,
                'protocol' => SupplierProtocol::Csv,
                'default_currency' => 'EUR',
                'timezone' => 'Europe/Warsaw',
                'priority' => 100,
                'qualification_score' => 83,
                'readiness_score' => 4,
                'supports_catalog' => true,
                'supports_prices' => true,
                'supports_stock' => true,
                'onboarding_notes' => '84.000+ referințe: ~55k anvelope, ~10,5k piese de service, scule, uleiuri și jante. Externalizare de fulfilment declarată pentru ecommerce auto în Polonia și Europa, livrare 48–72h.',
                'next_action' => 'Cere mostră de feed, matricea de transport către România și politica de colet neutru.',
                'sources' => ['https://partsman.pl/'],
                'unresolved' => ['colet neutru', 'suprimare factură', 'retururi', 'cadență feed', 'API comandă'],
            ],
            [
                'code' => 'NAP_CARPARTS',
                'name' => 'NAP carPARTS',
                'country_code' => 'DE',
                'website' => 'https://www.nap-carparts.com/',
                'supplier_type' => SupplierType::Distributor,
                'strategic_role' => SupplierStrategicRole::Specialist,
                'protocol' => SupplierProtocol::Api,
                'default_currency' => 'EUR',
                'timezone' => 'Europe/Berlin',
                'priority' => 100,
                'qualification_score' => 88,
                'readiness_score' => 5,
                'supports_catalog' => true,
                'supports_tecdoc' => true,
                'neutral_packaging' => true,
                'merchant_as_sender' => true,
                'onboarding_notes' => 'Specialist catalizatoare, DPF, evacuare și senzori aferenți. Declară expediere ambalată neutru, cu revânzătorul ca expeditor. Date compatibile TecDoc plus DVSE.',
                'next_action' => 'Cere integrarea API/ERP, tarifele de transport RO, detaliile API comandă/tracking și costul retururilor.',
                'sources' => ['https://www.nap-carparts.com/'],
                'unresolved' => ['transport RO', 'API comandă/tracking', 'cost retur'],
            ],
            [
                'code' => 'RIDEX',
                'name' => 'RIDEX',
                'country_code' => 'DE',
                'website' => 'https://en.ridex.eu/page/integrations',
                'supplier_type' => SupplierType::Distributor,
                'strategic_role' => SupplierStrategicRole::Backbone,
                'protocol' => SupplierProtocol::Api,
                'default_currency' => 'EUR',
                'timezone' => 'Europe/Berlin',
                'priority' => 100,
                'qualification_score' => 72,
                'readiness_score' => 4,
                'supports_catalog' => true,
                'supports_prices' => true,
                'supports_stock' => true,
                'supports_realtime_stock' => true,
                'supports_order_api' => true,
                'onboarding_notes' => 'Stack tehnic excelent: REST pentru stoc/prețuri real-time, detaliu produs și creare comandă, plus SFTP cu feed complet și actualizări orare de stoc/preț, 50.000+ SKU. DAR pagina publică nu garantează colet neutru către consumatorul final pentru orice cont B2B. Un API excelent nu înseamnă dropshipping.',
                'next_action' => 'NU porni sandbox tehnic înainte de confirmarea SCRISĂ a dropshipping-ului neutru către consumator, cu adresă de livrare arbitrară.',
                'sources' => ['https://en.ridex.eu/page/integrations'],
                'unresolved' => ['colet neutru', 'ship-to arbitrar', 'tarife și retururi RO'],
            ],
            [
                'code' => 'TYRECENTER',
                'name' => 'TyreCenter',
                'country_code' => 'RO',
                'website' => 'https://tyrecenter.com/en/contact/',
                'supplier_type' => SupplierType::Distributor,
                'strategic_role' => SupplierStrategicRole::Backbone,
                'protocol' => SupplierProtocol::Api,
                'default_currency' => 'RON',
                'timezone' => 'Europe/Bucharest',
                'priority' => 100,
                'qualification_score' => 87,
                'readiness_score' => 5,
                'offroad_fit_score' => 80,
                'supports_catalog' => true,
                'supports_prices' => true,
                'supports_stock' => true,
                'supports_realtime_stock' => true,
                'onboarding_notes' => 'Contrapondere locală la ALZURA/TASY/ViTire pentru anvelope: REST API cu feed de produs, stoc și preț în timp real, livrare directă către client promovată.',
                'next_action' => 'Cere credențiale API, taxele de dropship pentru România, endpointul de tracking, retururile și termenele de credit. Verifică adâncimea gamei A/T–M/T.',
                'sources' => ['https://tyrecenter.com/en/contact/'],
                'unresolved' => ['taxe dropship RO', 'endpoint tracking', 'retururi', 'gamă A/T–M/T'],
            ],
            [
                'code' => 'BIGBUY',
                'name' => 'BigBuy',
                'country_code' => 'ES',
                'website' => 'https://www.bigbuy.eu/en/dropshipping.html',
                'supplier_type' => SupplierType::Aggregator,
                'strategic_role' => SupplierStrategicRole::Longtail,
                'protocol' => SupplierProtocol::Api,
                'default_currency' => 'EUR',
                'timezone' => 'Europe/Madrid',
                'priority' => 150,
                'qualification_score' => 80,
                'readiness_score' => 5,
                'offroad_fit_score' => 58,
                'supports_catalog' => true,
                'supports_prices' => true,
                'supports_stock' => true,
                'supports_order_api' => true,
                'supports_tracking_api' => true,
                'onboarding_notes' => 'Platformă de dropship EU matură: API de catalog, comenzi, cost transport/curier și tracking, plus FTP CSV/XML. Automotive e categorie de accesorii, nu piese de fitment canonic. De folosit doar pentru long-tail, nu ca sursă de piese mecanice.',
                'next_action' => 'Evaluează abia după lansare. Verifică adâncimea automotive și marja față de competiția de marketplace.',
                'sources' => ['https://www.bigbuy.eu/en/dropshipping.html', 'https://www.bigbuy.eu/en/technology-dropshipping-wholesale-purchasing.html', 'https://www.bigbuy.eu/en/csv-xml-files.html'],
                'unresolved' => ['adâncime automotive', 'marjă vs marketplace', 'tarif RO curent'],
            ],
            [
                'code' => 'MAXY',
                'name' => 'Maxy.eu',
                'country_code' => 'PL',
                'website' => 'https://maxy.eu/hurt/pl_en/automotive.html',
                'supplier_type' => SupplierType::Wholesaler,
                'strategic_role' => SupplierStrategicRole::Longtail,
                'protocol' => SupplierProtocol::Xml,
                'default_currency' => 'EUR',
                'timezone' => 'Europe/Warsaw',
                'priority' => 150,
                'qualification_score' => 72,
                'readiness_score' => 3,
                'offroad_fit_score' => 69,
                'supports_catalog' => true,
                'minimum_order_value' => 120.00,
                'terms_currency' => 'EUR',
                'onboarding_notes' => 'Minim internațional publicat 120 EUR net. Rabat B2B pe cifra de afaceri 1–4%, credit comercial 7/14/21/30 zile pentru parteneri constanți. Interesant strategic pentru că își promovează explicit brandurile proprii/exclusive ca sursă de marjă cu mai puțină competiție directă de preț.',
                'next_action' => 'Clarifică dacă minimul de 120 EUR se aplică pe fiecare colet dropship sau doar pe comenzi angro. Cere costul curierului în România și regulile de retur.',
                'sources' => ['https://maxy.eu/hurt/pl_en/automotive.html'],
                'unresolved' => ['minim per colet dropship', 'cost curier RO', 'retururi'],
            ],
            [
                'code' => 'INTERCARS',
                'name' => 'Inter Cars',
                'country_code' => 'PL',
                'website' => 'https://intercars.com/en/business-solutions-inter-cars',
                'supplier_type' => SupplierType::Wholesaler,
                'strategic_role' => SupplierStrategicRole::Fallback,
                'protocol' => SupplierProtocol::Api,
                'default_currency' => 'EUR',
                'timezone' => 'Europe/Warsaw',
                'priority' => 150,
                'qualification_score' => 70,
                'readiness_score' => 4,
                'supports_catalog' => true,
                'supports_prices' => true,
                'supports_stock' => true,
                'supports_realtime_stock' => true,
                'supports_order_api' => true,
                'supports_tracking_api' => true,
                'supports_tecdoc' => true,
                'onboarding_notes' => 'Aproape 5 milioane de produse, 26 de țări. API HTTP/JSON cu preț și stoc pe locație în timp real, creare comandă, interogări financiare, status livrare și tracking; limită documentată 600 interogări/minut/client. Seturi CSV specifice clientului cu identificator TecDoc, EAN, producător și dimensiuni. Dropship-ul neutru B2C nu este stabilit public — întrebare comercială, nu blocaj tehnic.',
                'next_action' => 'Confirmare comercială înainte de orice cod: ship-to arbitrar, documente neutre, termeni pentru revânzător ecommerce din România.',
                'sources' => ['https://intercars.com/en/business-solutions-inter-cars/business-services/software/api-and-csv-employee-inter-cars'],
                'unresolved' => ['ship-to arbitrar', 'documente neutre', 'termeni revânzător RO'],
            ],
            [
                'code' => 'AUTOLINE_GR',
                'name' => 'Autoline Greece',
                'country_code' => 'GR',
                'website' => 'https://autoline.gr/en/partner-api/',
                'supplier_type' => SupplierType::Wholesaler,
                'strategic_role' => SupplierStrategicRole::Fallback,
                'protocol' => SupplierProtocol::Xml,
                'default_currency' => 'EUR',
                'timezone' => 'Europe/Athens',
                'priority' => 150,
                'qualification_score' => 72,
                'readiness_score' => 4,
                'supports_catalog' => true,
                'supports_prices' => true,
                'supports_stock' => true,
                'onboarding_notes' => 'Serviciu de date pentru parteneri în XML, CSV și JSON, feed reconstruit aproximativ orar, endpoint complet plus căutare pe articol, filtrare după stoc/tip/brand/categorie/SKU/dată modificare. Include GTIN-EAN, foto, specificații și greutate.',
                'next_action' => 'Confirmă tratamentul neutru al coletului și al facturii către clientul final înainte de implementare. Cere tarife RO și API de comandă.',
                'sources' => ['https://autoline.gr/en/partner-api/'],
                'unresolved' => ['colet/factură neutre', 'tarife RO', 'API comandă'],
            ],
            [
                'code' => 'ABS_BRAKES',
                'name' => 'A.B.S. All Brake Systems',
                'country_code' => 'NL',
                'website' => 'https://absallbrakesystems.com/',
                'supplier_type' => SupplierType::Manufacturer,
                'strategic_role' => SupplierStrategicRole::Specialist,
                'protocol' => SupplierProtocol::Api,
                'default_currency' => 'EUR',
                'timezone' => 'Europe/Amsterdam',
                'priority' => 150,
                'qualification_score' => 82,
                'readiness_score' => 5,
                'supports_catalog' => true,
                'supports_order_api' => true,
                'supports_tecdoc' => true,
                'onboarding_notes' => 'Frânare, direcție și rulmenți de roată, zeci de mii de articole în stoc. Dropship explicit. Comenzi prin webshop, import CSV, API sau TecCom — identificatorii TecCom/TecDoc simplifică maparea.',
                'next_action' => 'Cere pachetul de integrare API/TecCom, tarifele de transport în România și documentele către clientul final.',
                'sources' => ['https://absallbrakesystems.com/', 'https://absallbrakesystems.com/faq/'],
                'unresolved' => ['transport RO', 'documente client final'],
            ],
            [
                'code' => 'KROSFOU',
                'name' => 'Krosfou Group',
                'country_code' => 'FR',
                'website' => 'https://group.krosfou.com/',
                'supplier_type' => SupplierType::Manufacturer,
                'strategic_role' => SupplierStrategicRole::Specialist,
                'protocol' => SupplierProtocol::Manual,
                'default_currency' => 'EUR',
                'timezone' => 'Europe/Paris',
                'priority' => 150,
                'qualification_score' => 83,
                'readiness_score' => 4,
                'supports_tecdoc' => true,
                'onboarding_notes' => 'DPF-uri și catalizatoare, fabrică în Polonia. Oferă explicit stoc propriu, cross-docking la bucată sau dropshipping direct către clientul distribuitorului. Produsele sunt în TecDoc Germania. Nu a fost găsit un REST API public pentru revânzători.',
                'next_action' => 'Întreabă dacă automatizarea stoc/preț/comandă e disponibilă prin TecCom, feed sau API privat. Cere costul livrării în România.',
                'sources' => ['https://group.krosfou.com/'],
                'unresolved' => ['format API/feed', 'cost livrare RO', 'documente neutre'],
            ],
            [
                'code' => 'EASYPARTS',
                'name' => 'EasyParts',
                'country_code' => 'PL',
                'website' => 'https://easy-parts.pl/',
                'supplier_type' => SupplierType::Distributor,
                'strategic_role' => SupplierStrategicRole::Specialist,
                'protocol' => SupplierProtocol::Xml,
                'default_currency' => 'EUR',
                'timezone' => 'Europe/Warsaw',
                'priority' => 150,
                'qualification_score' => 79,
                'readiness_score' => 4,
                'supports_catalog' => true,
                'onboarding_notes' => 'Elemente de caroserie, dropshipping internațional explicit. Poate pregăti XML sau CSV în limba cerută, cu date de stoc și drept de folosire a imaginilor proprii. Piesele voluminoase cer modelare atentă a transportului și a retururilor deteriorate.',
                'next_action' => 'Cere mostră XML/CSV, cadența feedului, automatizarea comenzii și regulile pentru colete voluminoase deteriorate.',
                'sources' => ['https://easy-parts.pl/dropshipping-elementow-karoserii-samochodu'],
                'unresolved' => ['cadență feed', 'automatizare comandă', 'retur colete voluminoase'],
            ],
            [
                'code' => 'DDTUNING',
                'name' => 'DD Tuning',
                'country_code' => 'UA',
                'website' => 'https://dd-tuning.com/opt.html',
                'supplier_type' => SupplierType::Distributor,
                'strategic_role' => SupplierStrategicRole::Specialist,
                'protocol' => SupplierProtocol::Xml,
                'default_currency' => 'EUR',
                'priority' => 200,
                'qualification_score' => 78,
                'readiness_score' => 4,
                'offroad_fit_score' => 77,
                'supports_catalog' => true,
                'supports_prices' => true,
                'supports_stock' => true,
                'onboarding_notes' => 'Tuning și accesorii, XML/CSV/API cu descrieri, preț, stoc, imagini și specificații. ATENȚIE: expedierile pot porni din Ucraina, deci vama, TVA, Incoterms și SLA-ul de livrare se modelează separat de furnizorii cu stoc în UE.',
                'next_action' => 'Clarifică locația reală a stocului, SLA-ul către România, tratamentul vamal, documentele neutre și retururile.',
                'sources' => ['https://dd-tuning.com/opt.html'],
                'unresolved' => ['locație stoc', 'vamă/TVA', 'SLA RO', 'retururi'],
            ],
            [
                'code' => 'RACEORLY',
                'name' => 'Raceorly',
                'country_code' => 'DE',
                'website' => 'https://raceorly.de/',
                'supplier_type' => SupplierType::Distributor,
                'strategic_role' => SupplierStrategicRole::Specialist,
                'protocol' => SupplierProtocol::Manual,
                'default_currency' => 'EUR',
                'timezone' => 'Europe/Berlin',
                'priority' => 200,
                'qualification_score' => 70,
                'readiness_score' => 4,
                'supports_tecdoc' => true,
                'onboarding_notes' => 'Piese de motor/performanță, model dropship la bucată. Date orientate TecDoc. ATENȚIE: piesele pot proveni din producție/operațiuni chineze — stocul din UE, originea și tratamentul vamal/TVA trebuie verificate pe SKU și pe cont.',
                'next_action' => 'Verifică entitatea juridică și depozitul din UE înainte de orice dezvoltare.',
                'sources' => ['https://raceorly.de/'],
                'unresolved' => ['locație stoc UE', 'transport/retururi', 'automatizare comandă'],
            ],
            [
                'code' => 'KPB_PARTS',
                'name' => 'K.P.B. Parts',
                'country_code' => 'PL',
                'website' => 'https://kpb-parts.com/',
                'supplier_type' => SupplierType::Wholesaler,
                'strategic_role' => SupplierStrategicRole::Fallback,
                'protocol' => SupplierProtocol::Manual,
                'default_currency' => 'EUR',
                'timezone' => 'Europe/Warsaw',
                'priority' => 200,
                'qualification_score' => 64,
                'readiness_score' => 3,
                'onboarding_notes' => 'Branduri mainstream: ATE, Brembo, MANN, LuK, INA, FAG, Valeo, NGK, Bosch, Sachs, Febi. Livrare directă către clienții revânzătorului promovată, dar nu a fost găsită documentație publică de feed/API. Lead comercial, nu candidat de integrare.',
                'next_action' => 'Întreabă explicit de CSV/XML/JSON/SFTP, cadența de stoc și protocolul de comandă automată.',
                'sources' => ['https://kpb-parts.com/'],
                'unresolved' => ['feed de date', 'transport RO', 'fulfilment neutru', 'retururi'],
            ],
            [
                'code' => 'TYRE100',
                'name' => 'Tyre100 / Camodo Automotive',
                'country_code' => 'DE',
                'website' => 'https://www.tyre100.com/de-DE/',
                'supplier_type' => SupplierType::Marketplace,
                'strategic_role' => SupplierStrategicRole::Fallback,
                'protocol' => SupplierProtocol::Csv,
                'default_currency' => 'EUR',
                'timezone' => 'Europe/Berlin',
                'priority' => 200,
                'qualification_score' => 85,
                'readiness_score' => 5,
                'supports_catalog' => true,
                'supports_prices' => true,
                'supports_stock' => true,
                'supports_tecdoc' => true,
                'onboarding_notes' => 'Marketplace B2B care leagă cumpărătorii de anvelope/jante/piese de mai mulți angrosiști europeni. Fișiere de inventar furnizor prin FTP CSV, stoc și prețuri la nivel de furnizor, interfețe electronice de comandă. Furnizorii de piese trebuie să aibă date TecDoc. Candidat de agregare după ALZURA.',
                'next_action' => 'Clarifică scopul API-ului pe partea de cumpărător, transportul către România și branding-ul dropship per furnizor.',
                'sources' => ['https://www.tyre100.com/de-DE/'],
                'unresolved' => ['scop API cumpărător', 'transport RO', 'branding dropship'],
            ],
            [
                'code' => 'DELDO',
                'name' => 'Deldo',
                'country_code' => 'BE',
                'website' => 'https://www.deldo.com/',
                'supplier_type' => SupplierType::Wholesaler,
                'strategic_role' => SupplierStrategicRole::Fallback,
                'protocol' => SupplierProtocol::Api,
                'default_currency' => 'EUR',
                'timezone' => 'Europe/Brussels',
                'priority' => 200,
                'qualification_score' => 73,
                'readiness_score' => 4,
                'supports_catalog' => true,
                'supports_prices' => true,
                'supports_stock' => true,
                'onboarding_notes' => 'Distribuitor mare de anvelope. Conexiunea prin TyreAPI (terț) oferă stoc, prețuri și comenzi live. Dropship-ul cu etichetă neutră nu e documentat public la fel de clar ca la TASY sau ViTire.',
                'next_action' => 'Validare comercială și API înainte de a-l trata ca furnizor de lansare.',
                'sources' => ['https://www.deldo.com/en/homepage/are-2/a-huge-stock/a-lot-tyres/', 'https://tyreapi.com/products/supplier-connections/deldo'],
                'unresolved' => ['termeni direct-la-consumator RO', 'taxe', 'retururi'],
            ],
            [
                'code' => 'AUTODOC_PRO',
                'name' => 'AUTODOC PRO',
                'country_code' => 'DE',
                'website' => 'https://autodoc.group/',
                'supplier_type' => SupplierType::Marketplace,
                'onboarding_status' => SupplierOnboardingStatus::OnHold,
                'protocol' => SupplierProtocol::Manual,
                'default_currency' => 'EUR',
                'timezone' => 'Europe/Berlin',
                'priority' => 250,
                'qualification_score' => 55,
                'readiness_score' => 2,
                'onboarding_notes' => 'Platformă B2B profesională de anvergură, dar nu a fost identificat un API/feed public pentru revânzători care să alimenteze un catalog ecommerce independent. Contact strategic, nu sursă integrabilă. Scor sub 65 — nu se construiește primul.',
                'next_action' => 'Fără acțiune tehnică. Reevaluează dacă apare un program public de revânzător.',
                'sources' => ['https://autodoc.group/en/news-room/press-releases/autodoc-solidifies-european-leadership-with-strong-2025-performance/'],
                'unresolved' => ['feed/API revânzător', 'ship-to arbitrar', 'fulfilment B2C neutru'],
            ],
            [
                'code' => 'AUTO_PARTNER',
                'name' => 'Auto Partner SA',
                'country_code' => 'PL',
                'website' => 'https://www.autopartner.pl/',
                'supplier_type' => SupplierType::Wholesaler,
                'protocol' => SupplierProtocol::Csv,
                'default_currency' => 'EUR',
                'timezone' => 'Europe/Warsaw',
                'priority' => 250,
                'qualification_score' => 62,
                'readiness_score' => 3,
                'supports_catalog' => true,
                'onboarding_notes' => 'Angrosist polonez/central-european mare. Programele de comandă oferă date de produs, imagini, informații tehnice și conversie/export CSV/TXT/XML. Fulfilment direct către consumator nu a fost verificat public.',
                'next_action' => 'Întreabă dacă un revânzător ecommerce poate seta o adresă de livrare arbitrară, cu documente neutre și tracking electronic.',
                'sources' => ['https://www.autopartner.pl/oferta/programy-zamowieniowe'],
                'unresolved' => ['documentație API/feed', 'ship-to', 'documente neutre', 'logistică RO'],
            ],
            [
                'code' => 'AUTOAZ',
                'name' => 'AutoAZ',
                'country_code' => 'CZ',
                'website' => 'https://www.autoaz.com/',
                'supplier_type' => SupplierType::Wholesaler,
                'onboarding_status' => SupplierOnboardingStatus::OnHold,
                'protocol' => SupplierProtocol::Manual,
                'default_currency' => 'EUR',
                'timezone' => 'Europe/Prague',
                'priority' => 250,
                'qualification_score' => 52,
                'readiness_score' => 2,
                'onboarding_notes' => 'Catalog larg de piese de schimb, dar dovezile publice de feed și de dropship neutru au fost insuficiente. Scor sub 65 — se ține în așteptare.',
                'next_action' => 'Fără acțiune până apare documentație de partener.',
                'sources' => ['https://www.autoaz.com/'],
                'unresolved' => ['aproape toți termenii de fulfilment ecommerce'],
            ],
            [
                'code' => 'TRIALLIANCE',
                'name' => 'TriAlliance (BOGAP / CHITAO / ARAVOLT)',
                'country_code' => 'DE',
                'website' => 'https://www.atr.de/atr-supplier-recommendation-letter-trialliance/',
                'supplier_type' => SupplierType::Manufacturer,
                'strategic_role' => SupplierStrategicRole::Specialist,
                'protocol' => SupplierProtocol::Manual,
                'default_currency' => 'EUR',
                'timezone' => 'Europe/Berlin',
                'priority' => 200,
                'qualification_score' => 84,
                'readiness_score' => 5,
                'supports_tecdoc' => true,
                'onboarding_notes' => '30.000+ SKU: BOGAP 23k+ piese pentru vehicule europene, CHITAO 8,5k+ pentru mărci chinezești (MG, BYD, Chery, Geely), ARAVOLT pentru BEV/PHEV. Private labeling și dropshipping explicite, TecDoc + TecCom. Relevant strategic: piesele pentru mașini chinezești și EV vor conta tot mai mult în aftermarketul european și sunt mai puțin saturate decât service-ul ICE clasic.',
                'next_action' => 'Cere pachetul comercial: transport RO, documente neutre, detaliile feedului și ale API-ului de comandă.',
                'sources' => ['https://www.atr.de/atr-supplier-recommendation-letter-trialliance/'],
                'unresolved' => ['transport RO', 'documente neutre', 'detalii feed/API comandă'],
            ],
            [
                'code' => 'IKONKA',
                'name' => 'Ikonka',
                'country_code' => 'PL',
                'website' => 'https://www.ikonka.eu/en/wholesale-dropshipping',
                'supplier_type' => SupplierType::Wholesaler,
                'strategic_role' => SupplierStrategicRole::Longtail,
                'protocol' => SupplierProtocol::Xml,
                'default_currency' => 'EUR',
                'timezone' => 'Europe/Warsaw',
                'priority' => 250,
                'qualification_score' => 80,
                'readiness_score' => 3,
                'offroad_fit_score' => 64,
                'supports_catalog' => true,
                'minimum_order_value' => 0,
                'return_window_days' => 14,
                'onboarding_notes' => 'Dropshipping direct către client, fără valoare minimă de comandă, cu opțiunea etichetei proprii de curier; livrarea transfrontalieră cere etichetă proprie. XML a devenit abonament anual plătit de la 2025-09-01. Fitment slab pe vehicul — filler de accesorii mici, nu coloană de piese.',
                'next_action' => 'Evaluează costul abonamentului XML față de adâncimea reală a gamei automotive.',
                'sources' => ['https://www.ikonka.eu/en/wholesale-dropshipping', 'https://www.ikonka.eu/blog/en/dropshipping-2/dropshipping-forms-and-costs-of-delivery'],
                'unresolved' => ['cost abonament XML', 'transport RO cu etichetă proprie', 'adâncime automotive'],
            ],
            [
                'code' => 'SCT_MANNOL',
                'name' => 'SCT Germany / MANNOL',
                'country_code' => 'DE',
                'website' => 'https://www.mannol.de/de/dropshipping/',
                'supplier_type' => SupplierType::Manufacturer,
                'strategic_role' => SupplierStrategicRole::Specialist,
                'protocol' => SupplierProtocol::Xml,
                'default_currency' => 'EUR',
                'timezone' => 'Europe/Berlin',
                'priority' => 200,
                'qualification_score' => 88,
                'readiness_score' => 5,
                'supports_catalog' => true,
                'supports_prices' => true,
                'supports_stock' => true,
                'supports_order_api' => true,
                'supports_tracking_api' => true,
                'onboarding_notes' => 'Lubrifianți, filtre și consumabile de service sub portofoliul MANNOL/SCT. Dropshipping complet automatizat prin XML WebAPI, cu numere de transport returnate electronic; 5.000 mp dedicați, 2.000+ produse disponibile imediat. Categorie de cumpărare repetitivă, bună pentru completarea coșului.',
                'next_action' => 'Cere documentația XML WebAPI, discountul angro, lista SKU eligibile pentru dropship, transportul RO și retururile.',
                'sources' => ['https://www.mannol.de/de/dropshipping/'],
                'unresolved' => ['transport RO', 'discount angro', 'retururi', 'listă SKU eligibile'],
            ],
            [
                'code' => 'FORCETOP',
                'name' => 'Forcetop',
                'country_code' => 'PL',
                'website' => 'https://forcetop.com/',
                'supplier_type' => SupplierType::Wholesaler,
                'strategic_role' => SupplierStrategicRole::Longtail,
                'protocol' => SupplierProtocol::Xml,
                'default_currency' => 'EUR',
                'timezone' => 'Europe/Warsaw',
                'priority' => 200,
                'qualification_score' => 84,
                'readiness_score' => 5,
                'offroad_fit_score' => 72,
                'supports_catalog' => true,
                'supports_prices' => true,
                'supports_stock' => true,
                'merchant_as_sender' => true,
                'minimum_order_value' => 0,
                'onboarding_notes' => 'Livrare directă către clientul final în numele revânzătorului, fără achiziție minimă, inclusiv comandă la bucată. XML, CSV sau API pentru actualizarea automată a catalogului și stocului. Model operațional foarte curat.',
                'next_action' => 'Cere documentația API, tariful pentru România și regulile de retur. Validează adâncimea reală pe 4x4.',
                'sources' => ['https://forcetop.com/cs/about/-32'],
                'unresolved' => ['tarif RO', 'retururi', 'documentație API', 'specializare 4x4'],
            ],
            [
                'code' => 'SIGNEDA',
                'name' => 'Signeda',
                'country_code' => 'LT',
                'website' => 'https://www.signeda.lt/en/',
                'supplier_type' => SupplierType::Wholesaler,
                'strategic_role' => SupplierStrategicRole::Specialist,
                'protocol' => SupplierProtocol::Xml,
                'default_currency' => 'EUR',
                'timezone' => 'Europe/Vilnius',
                'priority' => 200,
                'qualification_score' => 76,
                'readiness_score' => 4,
                'offroad_fit_score' => 78,
                'supports_catalog' => true,
                'supports_prices' => true,
                'supports_stock' => true,
                'onboarding_notes' => 'Caroserie/exterior și, în special, piese pentru vehicule americane în Europa: 19M+ referințe de producător și 500k+ piese aftermarket declarate. Integratorii documentează API/XML/CSV/XLSX/XLS cu fluxuri automate de preț/stoc/comandă, dar asta trebuie confirmat direct în contractul B2B, nu preluat de la terți.',
                'next_action' => 'Aprobare de angro (analiză de manager ~24h), apoi cere pachetul API oficial, fulfilment-ul neutru și transportul/retururile RO.',
                'sources' => ['https://www.signeda.lt/en/', 'https://www.cezar.lt/lt/sprendimai/integracija/signeda-atsarginiu-automobiliu-daliu-b2b-dropshipping-tiekeju'],
                'unresolved' => ['documentație API first-party', 'fulfilment neutru', 'transport/retururi RO'],
            ],
            [
                'code' => '4CARS',
                'name' => '4CARS',
                'country_code' => 'SK',
                'website' => 'https://4cars.sk/',
                'supplier_type' => SupplierType::Distributor,
                'onboarding_status' => SupplierOnboardingStatus::OnHold,
                'protocol' => SupplierProtocol::Xml,
                'default_currency' => 'EUR',
                'timezone' => 'Europe/Bratislava',
                'priority' => 250,
                'qualification_score' => 48,
                'readiness_score' => 2,
                'supports_catalog' => true,
                'allowed_countries' => ['SK'],
                'onboarding_notes' => 'Accesorii auto cu feeduri XML/CSV regulate, dar condițiile B2B publice actuale limitează dropshipping-ul exclusiv la Slovacia. Contact util pentru o extindere viitoare, nu sursă de fulfilment pentru România azi.',
                'next_action' => 'Monitorizează. Niciun adaptor până când dropship-ul devine disponibil pentru România.',
                'sources' => ['https://4cars.sk/ro/content/15-cum-sa-devenii-partenerul-nostru-b2b-4-cars'],
                'unresolved' => ['disponibilitate dropship RO'],
            ],
        ];
    }

    /**
     * United States. Technically excellent for the 4x4 vertical, but for a
     * Romania-first operation cross-border parcel freight, import VAT/duty,
     * warranty returns, EU road-legality and delivery times make them unusable as
     * default consumer dropship sources. Held as market intelligence and as future
     * supply for a US storefront.
     *
     * @return list<array<string, mixed>>
     */
    private function unitedStatesSuppliers(): array
    {
        $shared = [
            'country_code' => 'US',
            'default_currency' => 'USD',
            'timezone' => 'America/New_York',
            'onboarding_status' => SupplierOnboardingStatus::OnHold,
            'priority' => 500,
        ];

        $suppliers = [
            [
                'code' => 'TURN14',
                'name' => 'Turn 14 Distribution',
                'website' => 'https://turn14.com/',
                'supplier_type' => SupplierType::Distributor,
                'strategic_role' => SupplierStrategicRole::Backbone,
                'protocol' => SupplierProtocol::Api,
                'qualification_score' => 95,
                'readiness_score' => 5,
                'offroad_fit_score' => 98,
                'supports_catalog' => true,
                'supports_prices' => true,
                'supports_stock' => true,
                'supports_realtime_stock' => true,
                'supports_order_api' => true,
                'supports_tracking_api' => true,
                'onboarding_notes' => 'Reper pentru cum arată o integrare matură de distribuitor specializat: API de produs și fitment, inventar live, fulfilment automat. Cere însă magazin/atelier profesional, licență de taxe de stat, cod fiscal federal și o comandă inițială obligatorie de deschidere.',
                'sources' => ['https://turn14.com/become_customer', 'https://news.turn14.com/2026/06/16/eating-our-own-cooking-building-e-commerce-with-the-turn-14-distribution-api/'],
            ],
            [
                'code' => 'APG_WHOLESALE',
                'name' => 'Aftermarket Performance Group (APG)',
                'website' => 'https://www.aftermarketperformancegroup.com/',
                'supplier_type' => SupplierType::Distributor,
                'strategic_role' => SupplierStrategicRole::Backbone,
                'protocol' => SupplierProtocol::Api,
                'qualification_score' => 94,
                'readiness_score' => 5,
                'offroad_fit_score' => 97,
                'supports_catalog' => true,
                'supports_prices' => true,
                'supports_stock' => true,
                'supports_order_api' => true,
                'supports_tracking_api' => true,
                'onboarding_notes' => '900k+ SKU de la 380+ producători de performanță. Rețeaua include afaceri 4x4 specializate precum Northridge4x4 și TrailRecon. Integrare API cu inventar orar, comenzi dropship automate și tracking.',
                'sources' => ['https://www.aftermarketperformancegroup.com/wholesale-capabilities-from-apg.html'],
            ],
            [
                'code' => 'FREEDOM_OFFROAD',
                'name' => 'Freedom Off-Road',
                'website' => 'https://freedomoffroadusa.com/dealers',
                'supplier_type' => SupplierType::Manufacturer,
                'strategic_role' => SupplierStrategicRole::Specialist,
                'protocol' => SupplierProtocol::Csv,
                'qualification_score' => 94,
                'readiness_score' => 4,
                'offroad_fit_score' => 97,
                'supports_catalog' => true,
                'supports_stock' => true,
                'supports_aces_pies' => true,
                'dropship_fee' => 0,
                'onboarding_notes' => 'Unul dintre cele mai curate programe de dealer găsite: fără comandă de deschidere, fără taxă de dropship, date ACES, feeduri de inventar, două depozite. Suspensie, brațe și amortizoare — exact miezul unui vertical 4x4.',
                'sources' => ['https://freedomoffroadusa.com/dealers'],
            ],
            [
                'code' => 'MOTORSTATE',
                'name' => 'Motor State Distributing',
                'website' => 'https://motorstate.com/business-tools/',
                'supplier_type' => SupplierType::Distributor,
                'strategic_role' => SupplierStrategicRole::Backbone,
                'protocol' => SupplierProtocol::Api,
                'qualification_score' => 95,
                'readiness_score' => 5,
                'offroad_fit_score' => 94,
                'supports_catalog' => true,
                'supports_prices' => true,
                'supports_stock' => true,
                'supports_order_api' => true,
                'supports_tracking_api' => true,
                'blind_shipping' => true,
                'onboarding_notes' => 'Dropship blind explicit, cu aviz de expediție personalizat și logo. Feed de inventar până la fiecare două ore, feed zilnic de 100k+ piese, API REST cu creare comandă, interogare, disponibilitate și estimare transport.',
                'sources' => ['https://motorstate.com/business-tools/', 'https://api.motorstate.com/swagger-ui/index.html'],
            ],
            [
                'code' => 'MEYER',
                'name' => 'Meyer Distributing',
                'website' => 'https://www.meyerdistributing.com/',
                'supplier_type' => SupplierType::Distributor,
                'strategic_role' => SupplierStrategicRole::Backbone,
                'protocol' => SupplierProtocol::Api,
                'qualification_score' => 88,
                'readiness_score' => 5,
                'offroad_fit_score' => 95,
                'supports_catalog' => true,
                'supports_prices' => true,
                'supports_stock' => true,
                'supports_order_api' => true,
                'supports_tracking_api' => true,
                'onboarding_notes' => 'Accesorii truck/SUV, Jeep/off-road, tractare, jante/anvelope. Portal B2B gratuit cu inventar în timp real pe mai multe depozite, creare/modificare comandă și tracking. ATENȚIE: politica de coliziune declară dropship-urile nereturnabile.',
                'sources' => ['https://www.meyerdistributing.com/Default.aspx?TabID=83&language=en-US'],
            ],
            [
                'code' => 'DSI_AUTOMOTIVE',
                'name' => 'DSI Automotive',
                'website' => 'https://www.dsiautomotive.com/',
                'supplier_type' => SupplierType::Distributor,
                'strategic_role' => SupplierStrategicRole::Specialist,
                'protocol' => SupplierProtocol::Manual,
                'qualification_score' => 88,
                'readiness_score' => 4,
                'offroad_fit_score' => 93,
                'onboarding_notes' => 'Agregator puternic de branduri truck/SUV. Demonstrează de ce costul de fulfilment trebuie să stea la nivel de SKU: paginile publice arată taxe de dropship de la ~5 USD la 70+ USD în funcție de produs, brand și transport, cu expunere suplimentară pe oversize/LTL. API extern public nu a fost găsit.',
                'sources' => ['https://www.dsiautomotive.com/dsi-account-application-policies'],
            ],
            [
                'code' => 'WHEELPROS',
                'name' => 'Wheel Pros',
                'website' => 'https://developer.wheelpros.com/',
                'supplier_type' => SupplierType::Distributor,
                'strategic_role' => SupplierStrategicRole::Specialist,
                'protocol' => SupplierProtocol::Api,
                'qualification_score' => 93,
                'readiness_score' => 5,
                'offroad_fit_score' => 91,
                'supports_catalog' => true,
                'supports_prices' => true,
                'supports_stock' => true,
                'supports_order_api' => true,
                'supports_tracking_api' => true,
                'onboarding_notes' => 'Cel mai bun portal public de developer găsit în US: API de autentificare, inventar pe depozit, prețuri MSRP/MAP/net, căutare produs, Vehicle Search API pe an/marcă/model/submodel, creare comandă, tracking, depozite și rapoarte.',
                'sources' => ['https://developer.wheelpros.com/'],
            ],
            [
                'code' => 'KEYSTONE_AUTO',
                'name' => 'Keystone Automotive Operations',
                'website' => 'https://sdkportal.ekeystone.com/',
                'supplier_type' => SupplierType::Distributor,
                'strategic_role' => SupplierStrategicRole::Fallback,
                'protocol' => SupplierProtocol::Api,
                'qualification_score' => 90,
                'readiness_score' => 5,
                'offroad_fit_score' => 89,
                'supports_catalog' => true,
                'supports_stock' => true,
                'supports_order_api' => true,
                'onboarding_notes' => 'Agregare foarte largă de accesorii truck/SUV, jante/anvelope. Portal SDK/developer cu API și FTP, sincronizare de produs, inventar și comenzi prin integrări partenere.',
                'sources' => ['https://sdkportal.ekeystone.com/Account/Login'],
            ],
            [
                'code' => 'REDLINE_AUTO',
                'name' => 'Redline Auto Supply',
                'website' => 'https://www.redlineautosupply.com/wholesale/',
                'supplier_type' => SupplierType::Distributor,
                'strategic_role' => SupplierStrategicRole::Specialist,
                'protocol' => SupplierProtocol::Csv,
                'qualification_score' => 92,
                'readiness_score' => 5,
                'offroad_fit_score' => 88,
                'supports_catalog' => true,
                'supports_prices' => true,
                'supports_stock' => true,
                'supports_aces_pies' => true,
                'blind_shipping' => true,
                'onboarding_notes' => 'Excelent candidat pentru un catalog US normalizat pe standardele Auto Care Association: ACES pentru fitment, PIES pentru informația de produs, EDI, CSV/XML zilnic. Expediere blind, fără branding sau factură Redline. MAP aplicat.',
                'sources' => ['https://www.redlineautosupply.com/wholesale/'],
            ],
            [
                'code' => 'WORLDPAC',
                'name' => 'WORLDPAC',
                'website' => 'https://developer.worldpac.com/oms/index.html',
                'supplier_type' => SupplierType::Distributor,
                'strategic_role' => SupplierStrategicRole::Backbone,
                'protocol' => SupplierProtocol::Api,
                'qualification_score' => 90,
                'readiness_score' => 5,
                'supports_catalog' => true,
                'supports_order_api' => true,
                'supports_tracking_api' => true,
                'supports_returns_api' => true,
                'onboarding_notes' => 'Unul dintre cele mai curate exemple de furnizor auto care expune dropshipping-ul ca operațiune API de prim rang, nu ca excepție manuală: documentația OMS include un flux dedicat Create a Drop-Ship Order, plus oferte, comenzi, retururi și informații de livrare.',
                'sources' => ['https://developer.worldpac.com/oms/index.html'],
            ],
            [
                'code' => 'LKQ_DROPSHIP',
                'name' => 'LKQ North America Drop Ship',
                'website' => 'https://lkqcorp.com/lkq-global_about-us/north-america/drop-ship/',
                'supplier_type' => SupplierType::Distributor,
                'strategic_role' => SupplierStrategicRole::Specialist,
                'protocol' => SupplierProtocol::Api,
                'qualification_score' => 90,
                'readiness_score' => 5,
                'supports_order_api' => true,
                'supports_tracking_api' => true,
                'onboarding_notes' => 'Program construit special pentru retaileri online: API de comandă care rutează către cel mai apropiat centru de distribuție, date de factură și tracking prin FTP. Acoperire unică pe piese de coliziune și recuperate, complementară aftermarketului nou.',
                'sources' => ['https://lkqcorp.com/lkq-global_about-us/north-america/drop-ship/'],
            ],
            [
                'code' => 'NOX_RD_USA',
                'name' => 'NOX RD USA',
                'website' => 'https://www.noxrdusa.com/pages/wholesale-dealer',
                'supplier_type' => SupplierType::Distributor,
                'strategic_role' => SupplierStrategicRole::Specialist,
                'protocol' => SupplierProtocol::Manual,
                'qualification_score' => 88,
                'readiness_score' => 4,
                'offroad_fit_score' => 89,
                'supports_catalog' => true,
                'onboarding_notes' => 'Program de angro care acceptă explicit magazine off-road/4x4, cu dropship direct către client, date de produs, imagini și fitment. Protocolul exact și taxele rămân private.',
                'sources' => ['https://www.noxrdusa.com/pages/wholesale-dealer'],
            ],
            [
                'code' => 'ATD',
                'name' => 'American Tire Distributors',
                'website' => 'https://www.atdonline.com/',
                'supplier_type' => SupplierType::Distributor,
                'strategic_role' => SupplierStrategicRole::Backbone,
                'protocol' => SupplierProtocol::Api,
                'qualification_score' => 84,
                'readiness_score' => 5,
                'supports_catalog' => true,
                'supports_prices' => true,
                'supports_stock' => true,
                'supports_order_api' => true,
                'supports_tracking_api' => true,
                'onboarding_notes' => 'Anvelope și jante, amprentă mare de distribuție în US. Sincronizare completă de catalog, cantitate și preț prin parteneri, comenzi dropship automate și tracking. Unele platforme cer o etapă de certificare în sandbox înainte de producție.',
                'sources' => ['https://www.atdonline.com/login'],
            ],
            [
                'code' => 'TIREHUB',
                'name' => 'TireHub',
                'website' => 'https://www.tirehub.com/',
                'supplier_type' => SupplierType::Distributor,
                'strategic_role' => SupplierStrategicRole::Fallback,
                'protocol' => SupplierProtocol::Api,
                'qualification_score' => 84,
                'readiness_score' => 5,
                'supports_catalog' => true,
                'supports_prices' => true,
                'supports_stock' => true,
                'supports_order_api' => true,
                'supports_tracking_api' => true,
                'onboarding_notes' => 'Distribuție națională de anvelope, susținută ca sursă de dropship în ecosistemul de integrare. Expune un mediu de administrare/înregistrare API pentru clienți.',
                'sources' => ['https://customers.web.middleware.tirehub.com/CustomerAPIAdmin/Registration'],
            ],
            [
                'code' => 'NTW',
                'name' => 'NTW — National Tire Wholesale',
                'website' => 'https://www.ntw.com/',
                'supplier_type' => SupplierType::Distributor,
                'strategic_role' => SupplierStrategicRole::Fallback,
                'protocol' => SupplierProtocol::Api,
                'qualification_score' => 84,
                'readiness_score' => 5,
                'offroad_fit_score' => 82,
                'supports_catalog' => true,
                'supports_prices' => true,
                'supports_stock' => true,
                'supports_realtime_stock' => true,
                'supports_order_api' => true,
                'onboarding_notes' => 'Endpointuri de developer pentru căutare produs, inventar și preț în timp real, plasare comandă, status, anulare și rezervare de stoc. Cererea de dealer recunoaște explicit afacerile off-road și de accesorii truck.',
                'sources' => ['https://www.ntw.com/'],
            ],
            [
                'code' => 'US_AUTOFORCE',
                'name' => 'U.S. AutoForce',
                'website' => 'https://www.usautoforce.com/',
                'supplier_type' => SupplierType::Distributor,
                'strategic_role' => SupplierStrategicRole::Fallback,
                'protocol' => SupplierProtocol::Api,
                'qualification_score' => 82,
                'readiness_score' => 5,
                'supports_catalog' => true,
                'supports_prices' => true,
                'supports_stock' => true,
                'supports_order_api' => true,
                'supports_tracking_api' => true,
                'onboarding_notes' => 'Anvelope și distribuție auto. Conectorii de furnizor oferă catalog, inventar și prețuri live, rutare de comenzi și tracking.',
                'sources' => ['https://www.usautoforce.com/'],
            ],
            [
                'code' => 'COVERCRAFT',
                'name' => 'Covercraft',
                'website' => 'https://dealer.covercraft.com/',
                'supplier_type' => SupplierType::Manufacturer,
                'strategic_role' => SupplierStrategicRole::Specialist,
                'protocol' => SupplierProtocol::Manual,
                'qualification_score' => 80,
                'readiness_score' => 4,
                'onboarding_notes' => 'Huse, covorașe și protecție interioară croite pe an/marcă/model — structură de fitment excelentă. Suportul first-party documentează un proces dedicat de comandă drop-ship către client sau adresă alternativă, dar nu a fost găsit un API public de volum.',
                'sources' => ['https://support.covercraft.com/hc/en-us/articles/40762753321371-Placing-a-Drop-Ship-Order'],
            ],
            [
                'code' => 'AMERICAN_MODIFIED',
                'name' => 'American Modified',
                'website' => 'https://americanmodified.com/',
                'supplier_type' => SupplierType::Manufacturer,
                'strategic_role' => SupplierStrategicRole::Specialist,
                'protocol' => SupplierProtocol::Manual,
                'qualification_score' => 76,
                'readiness_score' => 3,
                'offroad_fit_score' => 84,
                'onboarding_notes' => 'Accesorii și caroserie Jeep, Mustang și Honda, cu program explicit de dropship pentru revânzători. Fără API public; relația cu Keystone poate oferi o a doua rută de aprovizionare pentru unele SKU.',
                'sources' => ['https://americanmodified.com/en-ca/pages/become-a-reseller'],
            ],
            [
                'code' => 'COMP_SPECIALTIES',
                'name' => 'Competition Specialties (CSI)',
                'website' => 'https://compspecialties.com/',
                'supplier_type' => SupplierType::Distributor,
                'strategic_role' => SupplierStrategicRole::Fallback,
                'protocol' => SupplierProtocol::Manual,
                'qualification_score' => 75,
                'readiness_score' => 4,
                'onboarding_notes' => '145+ linii de produs, mai multe depozite și comandă angro în timp real, cu drop-ship fulfilment explicit. Documentație publică de API nu a fost găsită.',
                'sources' => ['https://compspecialties.com/'],
            ],
            [
                'code' => 'ANDERSON_COMPOSITES',
                'name' => 'Anderson Composites',
                'website' => 'https://andersoncomposites.com/dealers/',
                'supplier_type' => SupplierType::Manufacturer,
                'strategic_role' => SupplierStrategicRole::Specialist,
                'protocol' => SupplierProtocol::Manual,
                'qualification_score' => 74,
                'readiness_score' => 3,
                'offroad_fit_score' => 72,
                'dropship_fee' => 20.00,
                'terms_currency' => 'USD',
                'restocking_fee_percent' => 20.00,
                'onboarding_notes' => 'Caroserie și aero din fibră de carbon. Drop-ship permis, cu taxă publicată de 20 USD per comandă. MAP: prețul afișat nu mai mic de MSRP minus 10%. Retururile aprobate suportă 20% taxă de restocare și se creditează în magazin. Diferențiere de valoare mare, nu piese de reparație de volum.',
                'sources' => ['https://andersoncomposites.com/dealers/', 'https://andersoncomposites.com/shipping-and-returns/'],
            ],
        ];

        return array_map(
            static fn (array $supplier): array => [
                ...$shared,
                ...$supplier,
                'next_action' => 'Doar informație de piață până când există o entitate/magazin US. Pentru România, folosește lista ca sursă de branduri de căutat la distribuitorii lor din UE.',
                'unresolved' => ['entitate juridică US', 'certificat de revânzare / EIN', 'licență ACES/PIES', 'economie transfrontalieră'],
            ],
            $suppliers,
        );
    }
}
