<div>
    <div class="mb-6"><h1 class="text-2xl font-bold">Plăți și livrare</h1><p class="text-stone-500">Alegi procesatorul activ, mediul și curierul direct din admin. Secretele sunt criptate în baza de date.</p></div>
    @if(session('success'))<div class="mb-4 rounded-lg bg-lime-100 p-3 text-sm">{{ session('success') }}</div>@endif
    <form wire:submit="save" class="space-y-6">
        <section class="rounded-xl border bg-white p-5"><h2 class="mb-4 text-lg font-semibold">Procesatoare de plăți</h2><div class="space-y-4">@foreach($payments as $index=>$provider)<div class="grid gap-3 rounded-lg border p-4 md:grid-cols-3"><div><div class="font-semibold">{{ $provider['name'] }}</div><div class="text-xs text-stone-500">{{ $provider['configured'] ? 'Credentiale configurate' : 'Neconfigurat' }}</div></div><select wire:model="payments.{{ $index }}.mode" class="rounded border px-3 py-2"><option value="sandbox">Sandbox</option><option value="live">Live</option></select><div class="flex gap-4 text-sm"><label><input type="checkbox" wire:model="payments.{{ $index }}.is_active"> Activ</label><button type="button" wire:click="setDefaultPayment({{ $index }})" class="rounded px-2 py-1 {{ $provider['is_default'] ? 'bg-lime-200 font-semibold' : 'bg-stone-100' }}">{{ $provider['is_default'] ? 'Implicit' : 'Setează implicit' }}</button></div>
                @if($provider['code']==='stripe')<input type="password" wire:model="payments.{{ $index }}.credentials.publishable_key" placeholder="Publishable key (păstrează gol pentru neschimbat)" class="rounded border px-3 py-2"><input type="password" wire:model="payments.{{ $index }}.credentials.secret_key" placeholder="Secret key" class="rounded border px-3 py-2"><input type="password" wire:model="payments.{{ $index }}.credentials.webhook_secret" placeholder="Webhook signing secret" class="rounded border px-3 py-2">@else<input type="password" wire:model="payments.{{ $index }}.credentials.api_key" placeholder="NETOPIA API key" class="rounded border px-3 py-2"><input type="password" wire:model="payments.{{ $index }}.credentials.pos_signature" placeholder="POS signature" class="rounded border px-3 py-2">@endif
            </div>@endforeach</div></section>
        <section class="rounded-xl border bg-white p-5"><h2 class="mb-4 text-lg font-semibold">Curieri</h2>@foreach($shippingProviders as $index=>$provider)<div class="grid gap-3 rounded-lg border p-4 md:grid-cols-3"><div><div class="font-semibold">{{ $provider['name'] }}</div><div class="text-xs text-stone-500">{{ $provider['configured'] ? 'Credentiale configurate' : 'Neconfigurat' }}</div></div><select wire:model="shippingProviders.{{ $index }}.mode" class="rounded border px-3 py-2"><option value="sandbox">Sandbox</option><option value="live">Live</option></select><label class="text-sm"><input type="checkbox" wire:model="shippingProviders.{{ $index }}.is_active"> Activ</label><input type="password" wire:model="shippingProviders.{{ $index }}.credentials.token" placeholder="Token API FAN Courier" class="rounded border px-3 py-2"><input wire:model="shippingProviders.{{ $index }}.credentials.client_id" placeholder="Client ID" class="rounded border px-3 py-2"><input wire:model="shippingProviders.{{ $index }}.settings.service" placeholder="Serviciu (Standard)" class="rounded border px-3 py-2"></div>@endforeach</section>
        <section class="rounded-xl border bg-white p-5"><h2 class="mb-4 text-lg font-semibold">Metode și tarife de livrare</h2>@foreach($shippingMethods as $index=>$method)<div class="mb-3 grid gap-3 rounded-lg border p-4 md:grid-cols-6"><input wire:model="shippingMethods.{{ $index }}.name" class="rounded border px-3 py-2 md:col-span-2"><input type="number" step="0.01" wire:model="shippingMethods.{{ $index }}.base_price" placeholder="Tarif" class="rounded border px-3 py-2"><input type="number" step="0.01" wire:model="shippingMethods.{{ $index }}.free_over" placeholder="Gratuit peste" class="rounded border px-3 py-2"><input type="number" wire:model="shippingMethods.{{ $index }}.estimated_days_min" placeholder="Zile min" class="rounded border px-3 py-2"><input type="number" wire:model="shippingMethods.{{ $index }}.estimated_days_max" placeholder="Zile max" class="rounded border px-3 py-2"><label class="text-sm"><input type="checkbox" wire:model="shippingMethods.{{ $index }}.is_active"> Activă</label></div>@endforeach</section>
        <button class="rounded-lg bg-lime-400 px-6 py-2.5 font-bold">Salvează setările</button>
    </form>
</div>
