<div>
    <div class="mb-6 flex justify-between"><div><h1 class="text-2xl font-bold">Comanda {{ $freshOrder->number }}</h1><p class="text-stone-500">Plată, dropshipping, AWB și tracking.</p></div><a href="{{ route('admin.orders.index') }}" class="text-sm">← Comenzi</a></div>
    @if(session('success'))<div class="mb-4 rounded-lg bg-lime-100 p-3 text-sm">{{ session('success') }}</div>@endif
    <div class="grid gap-5 lg:grid-cols-3"><section class="rounded-xl border bg-white p-5 lg:col-span-2"><h2 class="mb-3 font-semibold">Produse</h2>@foreach($freshOrder->items as $item)<div class="flex justify-between border-t py-3 text-sm"><div>{{ $item->name }} <span class="text-stone-500">× {{ $item->quantity }}</span><div class="text-xs text-stone-400">{{ $item->sku }}</div></div><strong>{{ number_format($item->line_total,2,',','.') }} {{ $freshOrder->currency }}</strong></div>@endforeach<div class="mt-3 flex justify-between border-t pt-3 text-lg font-bold"><span>Total</span><span>{{ number_format($freshOrder->grand_total,2,',','.') }} {{ $freshOrder->currency }}</span></div></section><aside class="rounded-xl border bg-white p-5"><h2 class="font-semibold">Client & livrare</h2><p class="mt-2 text-sm">{{ $freshOrder->customer_email }}<br>{{ $freshOrder->customer_phone }}</p>@if($freshOrder->shippingAddress)<p class="mt-3 text-sm">{{ $freshOrder->shippingAddress->first_name }} {{ $freshOrder->shippingAddress->last_name }}<br>{{ $freshOrder->shippingAddress->line_1 }}<br>{{ $freshOrder->shippingAddress->city }}, {{ $freshOrder->shippingAddress->county }}</p>@endif</aside></div>
    <section class="mt-5 rounded-xl border bg-white p-5"><h2 class="mb-3 font-semibold">Tranzacții</h2>@forelse($freshOrder->payments as $payment)<div class="flex justify-between border-t py-3 text-sm"><span>{{ $payment->provider->name }} · {{ $payment->external_id }}</span><strong>{{ $payment->status }}</strong></div>@empty<p class="text-sm text-stone-500">Nicio tranzacție.</p>@endforelse</section>
    <section class="mt-5 rounded-xl border bg-white p-5"><h2 class="mb-3 font-semibold">Expedieri</h2>@foreach($freshOrder->shipments as $shipment)<div class="mb-3 rounded-lg border p-3"><div class="flex justify-between"><div><strong>{{ $shipment->provider->name }}</strong> · AWB {{ $shipment->awb_number }}<div class="text-sm text-stone-500">{{ $shipment->status }}</div></div><button wire:click="refreshTracking({{ $shipment->id }})" class="text-sm underline">Actualizează tracking</button></div>@foreach($shipment->events as $event)<div class="mt-2 border-t pt-2 text-xs">{{ $event->occurred_at->format('d.m.Y H:i') }} · {{ $event->description ?: $event->status }}</div>@endforeach</div>@endforeach
        @if($providers->isNotEmpty())<form wire:submit="createAwb" class="mt-4 grid gap-3 border-t pt-4 md:grid-cols-4"><select wire:model="shippingProviderId" class="rounded border px-3 py-2">@foreach($providers as $provider)<option value="{{ $provider->id }}">{{ $provider->name }}</option>@endforeach</select><input type="number" step="0.1" wire:model="weightKg" placeholder="Greutate kg" class="rounded border px-3 py-2"><input type="number" wire:model="pieces" placeholder="Colete" class="rounded border px-3 py-2"><button class="rounded bg-lime-400 px-4 py-2 font-semibold">Generează AWB</button></form>@else<p class="text-sm text-amber-700">Activează și configurează un curier înainte de generarea AWB.</p>@endif
    </section>
</div>
