<form wire:submit="save" class="space-y-6">
    <div><a href="{{ route('admin.catalog-platform.sources') }}" class="text-sm text-stone-500">← Catalog sources</a><h1 class="mt-2 text-2xl font-bold">{{ $source?->exists ? 'Edit source' : 'New source' }}</h1></div>
    @if(session('status'))<div class="rounded-lg bg-lime-100 p-3 text-sm text-lime-900">{{ session('status') }}</div>@endif
    <section class="grid gap-4 rounded-xl border bg-white p-5 md:grid-cols-2">
        <label class="space-y-1"><span class="text-sm font-medium">Name</span><input wire:model="name" class="w-full rounded border px-3 py-2">@error('name')<small class="text-red-600">{{ $message }}</small>@enderror</label>
        <label class="space-y-1"><span class="text-sm font-medium">Code</span><input wire:model="code" class="w-full rounded border px-3 py-2"></label>
        <label class="space-y-1"><span class="text-sm font-medium">Source type</span><input wire:model="sourceType" class="w-full rounded border px-3 py-2"></label>
        <label class="space-y-1"><span class="text-sm font-medium">Protocol</span><select wire:model="protocol" class="w-full rounded border px-3 py-2"><option>http</option><option>database</option><option>sftp</option><option>ftp</option><option>file</option></select></label>
        <label class="space-y-1 md:col-span-2"><span class="text-sm font-medium">Connector class</span><input wire:model="connectorClass" class="w-full rounded border px-3 py-2" placeholder="App\Catalog\Sources\Connectors\..."></label>
        <label class="space-y-1"><span class="text-sm font-medium">Base URL</span><input wire:model="baseUrl" class="w-full rounded border px-3 py-2"></label>
        <label class="space-y-1"><span class="text-sm font-medium">Catalog endpoint</span><input wire:model="catalogEndpoint" class="w-full rounded border px-3 py-2"></label>
    </section>
    <section class="rounded-xl border bg-white p-5"><h2 class="mb-4 font-bold">Rights</h2><div class="grid gap-4 md:grid-cols-2"><label><span class="text-sm">Rights class</span><select wire:model="rightsClass" class="mt-1 w-full rounded border px-3 py-2">@foreach($rightsClasses as $rights)<option value="{{ $rights->value }}">{{ $rights->value }}</option>@endforeach</select></label><label><span class="text-sm">License name</span><input wire:model="licenseName" class="mt-1 w-full rounded border px-3 py-2"></label><label class="md:col-span-2"><span class="text-sm">License URL</span><input wire:model="licenseUrl" class="mt-1 w-full rounded border px-3 py-2"></label></div><div class="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">@foreach(['allowInternal'=>'Internal','allowEcommerce'=>'Ecommerce','allowDerived'=>'Derived','allowApiRedistribution'=>'Public API','allowBulkExport'=>'Bulk export','allowMediaRedistribution'=>'Media redistribution','attributionRequired'=>'Attribution required','isActive'=>'Active'] as $property=>$label)<label class="flex items-center gap-2 rounded border p-3"><input type="checkbox" wire:model="{{ $property }}"><span class="text-sm">{{ $label }}</span></label>@endforeach</div><label class="mt-4 block"><span class="text-sm">Legal notes</span><textarea wire:model="legalNotes" rows="5" class="mt-1 w-full rounded border p-3"></textarea></label></section>
    <section class="grid gap-4 rounded-xl border bg-white p-5 xl:grid-cols-3"><label><span class="text-sm font-medium">Settings JSON</span><textarea wire:model="settingsJson" rows="14" class="mt-1 w-full rounded border p-3 font-mono text-xs"></textarea></label><label><span class="text-sm font-medium">Field mapping JSON</span><textarea wire:model="mappingJson" rows="14" class="mt-1 w-full rounded border p-3 font-mono text-xs"></textarea></label><label><span class="text-sm font-medium">Capabilities JSON</span><textarea wire:model="capabilitiesJson" rows="14" class="mt-1 w-full rounded border p-3 font-mono text-xs"></textarea></label></section>
    <button class="rounded-lg bg-lime-400 px-5 py-2.5 font-semibold text-stone-950">Save source</button>
</form>
