<?php

namespace App\Workshops\Sources\Rar;

/**
 * The registry's own wording for every code it uses, as published in the portal's Romanian
 * translation file (https://portal.rarom.ro/rar-public/assets/i18n/ro.json) on 2026-09-10.
 *
 * Only a fallback. workshops:rar:discover fetches the live file and stores it as a source record,
 * and RarNomenclature reads that copy first; this one answers when the portal cannot be reached.
 * Generated from the file, not typed: keep it that way when refreshing it.
 */
final class RarBundledNomenclature
{
    public const ACTIVITIES = [
        'SERVICE' => [
            'A1' => 'A1 Activități de reparații ale vehiculelor rutiere',
            'A1_1' => 'A1.1 Motor și sistemele auxiliare',
            'A1_1_1' => 'A1.1.1. mas şi mac',
            'A1_1_1_1' => 'A1.1.1.1. cu carburaţie şi/sau injecţie mecanică',
            'A1_1_1_2' => 'A1.1.1.2. cu injecţie cu gestiune electronică şi sisteme de depoluare',
            'A1_1_1_3' => 'A1.1.1.3. cu injecţie directă de înaltă presiune şi sisteme de depoluare',
            'A1_1_2' => 'A1.1.2. motoare hibride',
            'A1_1_3' => 'A1.1.3. motoare electrice',
            'A1_1_4' => 'A1.1.4. sisteme auxiliare',
            'A1_1_4_1' => 'A1.1.4.1. instalația de alimentare',
            'A1_1_4_2' => 'A1.1.4.2. instalația de răcire',
            'A1_1_4_3' => 'A1.1.4.3. instalația de evacuare',
            'A1_1_4_4' => 'A1.1.4.4. instalația de pornire',
            'A1_2' => 'A1.2 Sistemul de transmisie',
            'A1_2_1' => 'A1.2.1. transmisie mecanică',
            'A1_2_1_1' => 'A1.2.1.1. în trepte şi cu tracţiune pe o axă sau pe mai multe axe',
            'A1_2_1_2' => 'A1.2.1.2. în trepte, asistată şi cu tracţiune pe o axă sau pe mai multe axe',
            'A1_2_1_3' => 'A1.2.1.3. în trepte, asistată cu gestiune electronică şi cu tracţiune permanentă pe mai multe axe',
            'A1_2_2' => 'A1.2.2. transmisie automată',
            'A1_2_2_1' => 'A1.2.2.1. cu convertizor şi tracţiune pe o axă sau pe mai multe axe',
            'A1_2_2_2' => 'A1.2.2.2. cu convertizor gestionat electronic şi tracţiune pe o axă sau pe mai multe axe',
            'A1_2_2_3' => 'A1.2.2.3. cu convertizor gestionat electronic şi tracţiune permanentă pe mai multe axe',
            'A1_2_3' => 'A1.2.3. transmisie cu variator',
            'A1_2_3_1' => 'A1.2.3.1. cu variator mecanic',
            'A1_2_3_2' => 'A1.2.3.2. cu variator cu gestiune electronică',
            'A1_3' => 'A1.3 Sistemul de rulare',
            'A1_3_1' => 'A1.3.1. roţi',
            'A1_3_2' => 'A1.3.2. axe (punţi)',
            'A1_3_2_1' => 'A1.3.2.1. axe rigide',
            'A1_3_2_2' => 'A1.3.2.2. axe independente',
            'A1_3_3' => 'A1.3.3. suspensii',
            'A1_3_3_1' => 'A1.3.3.1. suspensie mecanică şi/sau mecano-hidraulică',
            'A1_3_3_1_1' => 'A1.3.3.1.1. suspensie mecanică',
            'A1_3_3_1_2' => 'A1.3.3.1.2. suspensie mecano-hidraulică',
            'A1_3_3_1_3' => 'A1.3.3.1.3. suspensie mecano-hidraulică cu gestiune electronică (activă)',
            'A1_3_3_2' => 'A1.3.3.2. suspensie pneumatică',
            'A1_3_3_2_1' => 'A1.3.3.2.1. cu reglare mecanică',
            'A1_3_3_2_2' => 'A1.3.3.2.2. cu gestiune electronică',
            'A1_4' => 'A1.4 Sistemul de direcție',
            'A1_4_1' => 'A1.4.1. fără asistare',
            'A1_4_2' => 'A1.4.2. cu asistare hidraulică',
            'A1_4_3' => 'A1.4.3. cu asistare electrică',
            'A1_5' => 'A1.5 Sistemul de frânare',
            'A1_5_1' => 'A1.5.1. sistem de frânare mecanic',
            'A1_5_2' => 'A1.5.2. sistem de frânare hidraulic',
            'A1_5_2_1' => 'A1.5.2.1. fără asistare',
            'A1_5_2_2' => 'A1.5.2.2. cu asistare şi fără sisteme avansate de control',
            'A1_5_2_3' => 'A1.5.2.3. cu asistare şi cu sisteme avansate de control',
            'A1_5_3' => 'A1.5.3. sistem de frânare pneumo-hidraulic şi/sau pneumatic',
            'A1_5_3_1' => 'A1.5.3.1. cu asistare şi fără sisteme avansate de control',
            'A1_5_3_2' => 'A1.5.3.2. cu asistare şi cu sisteme avansate de control',
            'A1_5_4' => 'A1.5.4. sistem de frânare electric',
            'A1_6' => 'A1.6 Sistemul electric',
            'A1_6_1' => 'A1.6.1. sistem electric clasic',
            'A1_6_2' => 'A1.6.2. sistem electric cu echipamente în reţea (CAN) cu şi fără circuit de înaltă tensiune',
            'A1_6_2_1' => 'A1.6.2.1. cu dispozitive optice clasice',
            'A1_6_2_2' => 'A1.6.2.2. cu dispozitive optice adaptive',
            'A1_7' => 'A1.7 Caroserie',
            'A1_7_1' => 'A1.7.1. caroserie autoportantă',
            'A1_7_1_1' => 'A1.7.1.1. repararea caroseriei fără intervenţii la structura de rezistenţă',
            'A1_7_1_2' => 'A1.7.1.2. repararea caroseriei cu intervenţii la structura de rezistenţă',
            'A1_7_1_3' => 'A1.7.1.3. redresarea structurii de rezistenţă',
            'A1_7_1_4' => 'A1.7.1.4. înlocuirea caroseriei',
            'A1_7_1_5' => 'A1.7.1.5. acoperirea anticorozivă',
            'A1_7_2' => 'A1.7.2. caroserie pe şasiu',
            'A1_7_2_1' => 'A1.7.2.1. repararea caroseriei fără intervenţii la şasiu',
            'A1_7_2_2' => 'A1.7.2.2. repararea şasiului',
            'A1_7_2_3' => 'A1.7.2.3. redresarea şasiului',
            'A1_7_2_4' => 'A1.7.2.4. înlocuirea şasiului',
            'A1_7_2_5' => 'A1.7.2.5. acoperirea anticorozivă',
            'A1_7_3' => 'A1.7.3 alte intervenţii la caroserie, inclusiv la amenajările interioare',
            'A1_8' => 'A1.8 Alte sisteme',
            'A1_8_1' => 'A1.8.1. sisteme de reţinere',
            'A1_8_1_1' => 'A1.8.1.1. cu centuri de siguranţă clasice',
            'A1_8_1_2' => 'A1.8.1.2. cu centuri de siguranţă cu pretensionare în caz de impact',
            'A1_8_1_3' => 'A1.8.1.3. cu alte sisteme de reţinere',
            'A1_8_2' => 'A1.8.2. sisteme electronice de asistenţă a conducătorului auto',
            'A1_8_2_1' => 'A1.8.2.1. sistem adaptiv de menţinere a vitezei',
            'A1_8_2_2' => 'A1.8.2.2. sistem de avertizare la schimbarea benzii de circulaţie',
            'A1_8_2_3' => 'A1.8.2.3. sistem automat de evitare şi atenuare a impactului',
            'A1_8_2_4' => 'A1.8.2.4. alte sisteme',
            'A1_8_3' => 'A1.8.3. sisteme de vizibilitate directă şi indirectă',
            'A1_8_4' => 'A1.8.4. sisteme de încălzire, de climatizare şi/sau de refrigerare',
            'A1_8_4_1' => 'A1.8.4.1. cu sursă de energie de la motorul de tracţiune',
            'A1_8_4_2' => 'A1.8.4.2. independente',
            'A2' => 'A2 Activități de întreținere a vehiculelor rutiere',
            'A2_1' => 'A2.1 Înlocuire ulei',
            'A2_2' => 'A2.2 Înlocuire filtre',
            'A2_3' => 'A2.3 Înlocuire plăcuțe de frână',
            'A2_4' => 'A2.4 Înlocuire lichide',
            'A2_5' => 'A2.5 Înlocuire becuri și siguranțe',
            'A2_6' => 'A2.6 Înlocuire curele de transmisie',
            'A2_7' => 'A2.7 Înlocuire agent refrigerent',
            'A3' => 'A3 Activități de reglări funcționale ale vehiculelor rutiere',
            'A3_1' => 'A3.1 reglarea geometriei sistemului de direcție',
            'A3_2' => 'A3.2 reglarea sistemelor de gestiune electronică',
            'B1' => 'B1 Activități de reparații ale componentelor și ale sistemelor vehiculelor rutiere',
            'B1_1' => 'B1.1 Motor și sistemele auxiliare și componentele acestora',
            'B1_2' => 'B1.2 Sistemul de transmisie și componentele acestuia',
            'B1_3' => 'B1.3 Sistemul de rulare și componentele acestuia',
            'B1_4' => 'B1.4 Sistemul de direcție și componentele acestuia',
            'B1_5' => 'B1.5 Sistemul de frânare și componentele acestuia',
            'B1_6' => 'B1.6 Sistemul electric și componentele acestuia',
            'B1_7' => 'B1.7 Caroserie și componentele acesteia',
            'B1_8' => 'B1.8 Alte sisteme și componentele acestora',
            'B2' => 'B2 Activități de recondiționări ale componentelor și ale sistemelor vehiculelor rutiere',
            'B2_1' => 'B2.1. motor şi sistemele auxiliare şi componentele acestora',
            'B2_2' => 'B2.2. sistemul de transmisie şi componentele acestuia',
            'B2_3' => 'B2.3. sistemul de rulare şi componentele acestuia',
            'B2_4' => 'B2.4. sistemul de direcţie şi componentele acestuia',
            'B2_5' => 'B2.5. sistemul de frânare şi componentele acestuia',
            'B2_6' => 'B2.6. sistemul electric şi componentele acestuia',
            'B2_7' => 'B2.7. caroserie şi componentele acesteia',
            'B2_8' => 'B2.8. alte sisteme şi componentele acestora',
            'B3' => 'B3 Activități de montări, verificări și/sau etalonări ale componentelor și ale sistemelor vehiculelor rutiere',
            'B3_1' => 'B3.1. sistemul de evacuare prevăzut cu dispozitive pentru controlul poluării și componentele acestuia',
            'B3_2' => 'B3.2. instalația de alarmă auto (inclusiv de tip GPS) și închidere centralizată și componentele acestora',
            'B3_3' => 'B3.3. instalații audio, video (aparate radio, CD, casetofon, DVD sau combinații ale acestora) și de sonorizare și componentele acestora',
            'B3_4' => 'B3.4. instalații de climatizare cu funcționare integrată sau independentă specifice auto și componentele acestora',
            'B5' => 'B5 Activități de dezmembrare a vehiculelor rutiere scoase din uz',
            'B5_1' => 'B5.1. dezmembrarea vehiculelor scoase din uz',
            'B5_2' => 'B5.2. dezmembrarea subansamblurilor vehiculelor rutiere',
        ],
        'SERVICE_A1_7' => [
            'A1_7_1_4' => 'A1.7.1.4. înlocuirea caroseriei',
            'A1_7_2_4' => 'A1.7.2.4. înlocuirea şasiului',
        ],
        'SERVICE_B5' => [
            'B5_1' => 'B5.1. dezmembrarea vehiculelor scoase din uz',
            'B5_2' => 'B5.2. dezmembrarea subansamblurilor vehiculelor rutiere',
        ],
        'B4' => [
            'B4_1_1' => 'B4.1.1. montarea de caroserii pentru vehicule rutiere',
            'B4_1_2' => 'B4.1.2. conversia şi/sau amenajarea vehiculelor rutiere',
            'B4_1_3' => 'B4.1.3. montarea şi/sau modificarea de componente şi/sau sisteme, dacă afectează caracteristicile de omologare',
            'B4_2' => 'B4.2. Reconstrucţia vehiculelor rutiere',
        ],
        'GPL' => [
            'GPL_INST_GPL' => 'Montarea instalațiilor de alimentare cu GPL',
            'GPL_INST_GNC' => 'Montarea instalațiilor de alimentare cu GNC',
            'GPL_INSP_GPL' => 'Revizia tehnică a instalațiilor de alimentare cu GPL',
            'GPL_INSP_GNC' => 'Revizia tehnică a instalațiilor de alimentare cu GNC',
            'GPL_FIX_GPL' => 'Repararea instalațiilor de alimentare cu GPL',
            'GPL_FIX_GNC' => 'Repararea instalațiilor de alimentare cu GNC',
        ],
        'TLV' => [
            'TLV_INSP' => 'Inspecții tahografe şi/sau limitatoare de viteză',
            'TLV_INST' => 'Instalare tahografe şi/sau limitatoare de viteză',
            'TLV_REPLACE' => 'Reparare prin înlocuire de componente',
            'TLV_FIX' => 'Reparare care necesită desfacere carcasă',
        ],
        'ITP' => [
            'ITP' => 'Activități de Inspecție tehnică periodică',
            'ITP_CLASS_1' => 'Clasa I',
            'ITP_CLASS_2' => 'Clasa II',
            'ITP_CLASS_3' => 'Clasa III',
        ],
    ];

    public const CLASSES = [
        'SERVICE' => [
            'CLASS_1' => 'CLASA I',
            'CLASS_2' => 'CLASA II',
            'CLASS_3' => 'CLASA III',
        ],
        'SERVICE_A1_7' => [
            'CLASS_1' => 'CLASA I',
            'CLASS_2' => 'CLASA II',
            'CLASS_3' => 'CLASA III',
        ],
        'SERVICE_B5' => [
            'CLASS_1' => 'CLASA I',
            'CLASS_2' => 'CLASA II',
        ],
        'ITP' => [
            'ITP_CLASS_1' => 'CLASA I',
            'ITP_CLASS_2' => 'CLASA II',
            'ITP_CLASS_3' => 'CLASA III',
        ],
        'B4' => [],
        'GPL' => [],
        'TLV' => [],
    ];

    public const VEHICLE_CATEGORIES = [
        'L' => 'L',
        'L1_E' => 'L1e',
        'L2_E' => 'L2e',
        'L3_E' => 'L3e',
        'L4_E' => 'L4e',
        'L5_E' => 'L5e',
        'L6_E' => 'L6e',
        'L7_E' => 'L7e',
        'L1e' => 'L1e',
        'L2e' => 'L2e',
        'L3e' => 'L3e',
        'L4e' => 'L4e',
        'L5e' => 'L5e',
        'L6e' => 'L6e',
        'L7e' => 'L7e',
        'M' => 'M',
        'M1' => 'M1',
        'M2' => 'M2',
        'M3' => 'M3',
        'N' => 'N',
        'N1' => 'N1',
        'N2' => 'N2',
        'N3' => 'N3',
        'O' => 'O',
        'O1' => 'O1',
        'O2' => 'O2',
        'O3' => 'O3',
        'O4' => 'O4',
        'G' => 'G',
        'SPEC' => 'VEHICULE SPECIALE',
        'T' => 'T',
        'T1' => 'T1',
        'T2' => 'T2',
        'T3' => 'T3',
        'T4' => 'T4',
        'T4_1' => 'T 4.1',
        'T4_2' => 'T 4.2',
        'T4_3' => 'T 4.3',
        'T5' => 'T5',
        'C' => 'C',
        'R' => 'R',
        'R1' => 'R1',
        'R2' => 'R2',
        'R3' => 'R3',
        'R4' => 'R4',
        'S' => 'S',
        'S1' => 'S1',
        'S2' => 'S2',
        'MAL' => 'MAL',
    ];

    public const B4_COMPONENTS = [
        'C1' => 'Baterii de acumulatori suplimentare',
        'C2' => 'Cabine/cușete de dormit',
        'C3' => 'Componente electro-mecano-pneumatice, utilizate la modificarea instalației electrice a autovehiculelor, în vederea îndeplinirii cerințelor ADR pentru transportul mărfurilor periculoase. Tipuri vehicule: FL/AT/EXII/EXIII/OX.',
        'C4' => 'Convertizoare catalitice',
        'C5' => 'Deflectoare de aer - paravânt',
        'C6' => 'Dispozitiv de comandă manuală semnalizator/ștergătoare',
        'C7' => 'Dispozitive antiblocare pentru sisteme de frânare pneumatice (ABS)',
        'C8' => 'Dispozitive de comandă dublă pentru ambreiaj, frână de serviciu și accelerație destinat autovehiculelor pentru școala de șoferi',
        'C9' => 'Dispozitive de protecție frontală (Bullbar-uri)',
        'C10' => 'Dispozitive electronice de limitare a vitezei',
        'C11' => 'Dispozitive mecanice de cuplare',
        'C12' => 'Dispozitive mecanice de cuplare a semiremorcilor cu destinație specială de transport bușteni',
        'C13' => 'Dispozitive pneumatice de suplimentare a suspensiei mecanice',
        'C14' => 'Dispozitiv sferic de comanda pe volan',
        'C15' => 'Dispozitive mecanice de comandă manuala a pedalelor de frână și accelerație',
        'C16' => 'Echipamente medicale pentru autovehicule ambulanță',
        'C17' => 'Echipamente speciale de avertizare optico-acustice',
        'C18' => 'Echipamente speciale de transmisiuni radio și tv',
        'C19' => 'Folii pentru geamurile de securitate (altele decât parbrizele) aflate în câmpul de vizibilitate spre înainte al conducătorului auto.',
        'C20' => 'Folii pentru geamurile de securitate (altele decât parbrizele) aflate în câmpul de vizibilitate spre înainte al conducătorului auto. Se utilizează și tehnologia de aplicare cu demontarea geamurilor.',
        'C21' => 'Folii pentru geamurile de securitate aflate în câmpul de vizibilitate spre înapoi al conducătorului auto.',
        'C22' => 'Folii pentru geamurile de securitate aflate în câmpul de vizibilitate spre înapoi al conducătorului auto. Se utilizează și tehnologia de aplicare cu demontarea geamurilor.',
        'C23' => 'Geamuri de securitate semicolorate (altele decât parbrizele) aflate în câmpul de vizibilitate spre înainte al conducătorului auto.',
        'C24' => 'Geamuri de securitate semicolorate aflate în câmpul de vizibilitate spre înapoi al conducătorului auto.',
        'C25' => 'Montajului de suprastructuri tip hardtop',
        'C26' => 'Montat/demontat geamuri amenajare specifică habitaclu',
        'C27' => 'Montat/demontat panou despărțitor',
        'C28' => 'Montat/demontat scaune/strapontine/banchete',
        'C29' => 'Pereți despărțitori pentru autovehicule utilizate la transportul în regim de taxi',
        'C30' => 'Portbagaje cu suport de scară',
        'C31' => 'Reamplasare dispozitive de comandă manuală semnalizator/ștergătoare',
        'C32' => 'Reamplasare pedala de acceleratie (pentru autovehiculele cu cutie de viteze automată/fără pedală de ambreiaj) ',
        'C33' => 'Scaune/Banchete suplimentare și pereți despărțitori',
        'C34' => 'Sisteme de aer condiționat',
        'C35' => 'Sisteme de încălzire independentă',
        'C36' => 'Sisteme de prelate și structuri de susținere pentru acestea',
        'C37' => 'Sisteme de suspensie pneumatică',
        'C38' => 'Sisteme de transmisie auxiliară, combinate mecanic/hidrostatic',
        'C39' => 'Sisteme electro-hidraulice pentru basculare',
        'C40' => 'Sisteme electro-mecanice de tracțiune cu fir textil sau din oțel(trolii)',
        'C41' => 'Sisteme electronice pentru creșterea puterii motoarelor',
        'C42' => 'Sisteme frigorifice',
        'C43' => 'Sisteme hidraulice de ridicat/lifturi/rampe pentru accesul persoanelor cu dizabilități',
        'C44' => 'Sisteme hidraulice de ridicat/macarale/lifturi',
        'C45' => 'Sisteme hidraulice de ridicat/obloane ridicatoare',
        'C46' => 'Sisteme hidraulice/Suport frontal pentru echipamente de lucrări stradale (lame, pluguri, freze de zăpadă, perii maturătoare, stropitori aspiratoare praf/frunze)',
        'C47' => 'Sisteme/celule de cantarire pe autospeciale SG 18 vehicul de colectat gunoi',
        'C48' => 'Structură exterioară tip cadru pentru protecție la răsturnare',
        'C49' => 'Suprastructură specială destinată împrăștierii materialelor antiderapante',
        'C50' => 'Suprastructură specială destinată împrăștierii îngrășămintelor agricole',
        'C51' => 'Suprastructură specială transport containere',
        'C52' => 'Suprastructuri tip cisternă specifice transportului de mărfuri ADR',
        'C53' => 'Tuning motor/Modificare soft pentru creșterea puterii motoarelor',
        'C54' => 'Tuning/Dispozitive de iluminare și semnalizare',
        'C55' => 'Tuning/Elemente ale sistemului de frânare',
        'C56' => 'Tuning/Elemente ale sistemului de suspensie',
        'C57' => 'Tuning/Elemente ornamentale destinate exteriorului caroseriei ( eleroane, praguri laterale, spoilere, grile)',
        'C58' => 'Tuning/Elemente ornamentale destinate interiorului/habitaclului caroseriei',
        'C59' => 'Tuning/ Roți din aliaj ușor',
        'C60' => 'Agregat de pompare/instalație de înaltă presiune ',
        'C61' => 'Amenajare interioare/exterioare specifică intervenții service mobil, marca TECNOLAM',
        'C62' => 'Aparate pentru măsurarea vitezei de circulaţie a autovehiculelor',
        'C63' => 'Ataşe moto',
        'C64' => 'Axe suplimentare cu sistem de frânare ABS',
        'C65' => 'Dispozitiv suport roată de rezervă',
        'C66' => 'Dispozitive suplimentare electromagnetice pentru sisteme de frânare (frână de încetinire/retarder)',
        'C67' => 'Dispozitiv de protecţie în dreptul golului de scară',
        'C68' => 'Echipamente speciale - utilaj pentru compactare deşeuri metalice',
        'C69' => 'Echipare specială a sistemului de alimentare pentru modificarea motoarelor MAC in MAS cu alimentare cu GNC',
        'C70' => 'Echipare specială a sistemului de alimentare pentru modificarea motoarelor MAC in MAS cu alimentare cu GPL',
        'C71' => 'Echipare specială pentru modificarea propulsiei autoturismelor cu motoare termice în autoturisme cu motoare electrice',
        'C72' => 'Generatoare de curent cu motor termic',
        'C73' => 'Sisteme de calare',
        'C74' => 'Sisteme de transmisie pentru echipamente auxiliare',
        'C75' => 'Sisteme de transvazare/pompe înalta presiune pentru apă',
        'C76' => 'Sisteme electronice pentru măsurarea consumului de combustibil',
        'C77' => 'Sisteme electronice/software pentru scăderea puterii motoarelor/revenirea la puterea inițială',
        'C78' => 'Sisteme mecanice pentru scăderea puterii motoarelor/revenirea la puterea inițială',
        'C79' => 'Sisteme speciale de curăţare / gresare reductoare',
        'C80' => 'Uși metalice la caroseriile tip furgon cu prelată, în locul oblonului spate și prelatei spate',
        'C81' => 'Sisteme hidraulice de ridicare',
        'C82' => 'Echipament de recuperare tip troliu',
        'C83' => 'Folie publicitară, perforată, pe exteriorul geamurilor de securitate aflate în câmpul de vizibilitate spre înapoi al conducătorului auto.',
        'C84' => 'Incinte/cutii blindate, certificate ICECON, pentru autospeciale transport valori',
        'C85' => 'Tuning/Elemente ale sistemului de direcție',
        'C86' => 'Echipamente speciale de emisie/recepție radio',
        'C87' => 'Dispozitiv de comandă manuală ambreiaj, destinat persoanelor cu handicap locomotor',
        'C88' => 'Geamuri de securitate semicolorate (altele decât parbrizele) aflate în câmpul de vizibilitate spre înainte al conducătorului auto',
        'C89' => 'Geamuri de securitate semicolorate aflate în câmpul de vizibilitate spre înapoi al conducătorului auto',
        'C90' => 'Scaune/Banchete suplimentare',
        'C91' => 'Dispozitive mecanice de comandă manuală a pedalelor de ambreiaj, accelerație și frână',
    ];

    public const ITP_CLASSES = [
        'ITP_CLASS_1' => 'Clasa I de autorizare ITP - mopede, motociclete, mototricicluri, cvadricicluri și remorcile acestora',
        'ITP_CLASS_2' => 'Clasa II de autorizare ITP - vehicule cu MTMA până la 3.500 kg. inclusiv, cu excepția celor din clasa I',
        'ITP_CLASS_3' => 'Clasa III de autorizare ITP - vehicule cu MTMA mai mare de 3.500 kg.',
    ];

    public const ITP_LIMITATIONS = [
        'ITP_LIMITATION_Hmax_AUTO' => 'Înălțime maximă autovehicul Hmax=@param',
        'ITP_LIMITATION_Lmax_AUTO' => 'Lungime maximă autovehicul Lmax=@param',
        'ITP_LIMITATION_lmax_AUTO' => 'Lățime maximă autovehicul lmax=@param',
        'ITP_LIMITATION_dmin' => 'Distanță minimă între fețele interioare ale anvelopelor dmin=@param',
        'ITP_LIMITATION_Amax_AUTO' => 'Ampatament maxim autovehicul Amax=@param',
        'ITP_LIMITATION_Amax_VEHICLE' => 'Ampatament maxim vehicul Amax=@param',
        'ITP_LIMITATION_MAL' => 'Inclusiv M.A.L.',
        'ITP_LIMITATION_Emax_VEHICLE' => 'Ecartament maxim vehicul Emax=@param',
        'ITP_LIMITATION_Mmax_AUTO' => 'Masă autovehicul Mmax=@param',
        'ITP_LIMITATION_Dmax_SEAT_AUTO' => 'Distanța maximă între axa spate și postul de conducere al autovehiculului Dmax=@param',
        'ITP_LIMITATION_Dmax_SEAT_ASSEMBLY' => 'Distanța maximă între axa spate și postul de conducere al ansamblului de vehicule Dmax=@param',
        'ITP_LIMITATION_Dmax_CONSOLE_AUTO' => 'Distanța maximă între axa spate și extremitatea consolei față a autovehiculului Dmax=@param',
        'ITP_LIMITATION_Hmax_VEHICLE' => 'Înălțime maximă vehicul Hmax=@param',
        'ITP_LIMITATION_Mmax_AXLE' => 'Masă maximă pe axă Mmax=@param',
        'ITP_LIMITATION_Lmax_AUTO_ASSEMLY' => 'Lungime maximă autovehicul sau ansamblu de vehicule Lmax=@param',
        'ITP_LIMITATION_lmax_VEHICLE' => 'Lățime maximă autovehicul lmax=@param',
        'ITP_LIMITATION_DMAX_TIRES_13_28' => 'Dimensiune maximă a anvelopelor 13.6-28 sau echivalente',
        'ITP_LIMITATION_DMAX_TIRES_14_38' => 'Dimensiune maximă a anvelopelor 14.00-38 sau echivalente',
        'ITP_LIMITATION_Lmax_BETWEEN_AXLES' => 'Distanța maximă între prima și ultima axă a autovehiculului Lmax=@param',
        'ITP_LIMITATION_Lmax_BETWEEN_AXLES_VEHICLE' => 'Distanța maximă între prima și ultima axă a vehiculului',
        'ITP_LIMITATION_Lmax_VEHICLE' => 'Lungime maximă vehicul Lmax=@param',
        'ITP_LIMITATION_Dmax_AUTO_ASSEMLY' => 'Distanța maximă de la axa spate la postul de conducere al autovehicului sau ansamblului de vehicule Dmax=@param',
        'ITP_LIMITATION_dmax_TIRES' => 'Distanța maximă între fețele exterioare ale anvelopelor dmax=@param',
        'ITP_LIMITATION_Amin_AUTO' => 'Ampatament minim autovehicul Amin=@param',
        'ITP_LIMITATION_Dmax_CONSOLE_AUTO_ASSEMLY' => 'Distanța maximă între axa spate și extremitatea consolei față a autovehiculului sau ansamblului de vehicule Dmax=@param',
        'ITP_LIMITATION_Dmax_CONSOLE_BACK' => 'Distanța maximă de la axa față la extremitatea consolei spate Lmax=@param',
        'ITP_LIMITATION_Omax_CONSOLE_AUTO' => 'Consolă față autovehicul Omax=@param',
        'ITP_LIMITATION_lmax_TIRES' => 'Lățime maximă anvelope lmax=@param',
        'ITP_LIMITATION_Lmax_ASSEMLY' => 'Lungime maximă ansamblu de vehicule Lmax=@param',
        'ITP_LIMITATION_Dmax_CONSOLE_ASSEMLY' => 'Distanța maximă de la axa spate la extremitatea consolei față a ansamblului de vehicule Lmax=@param',
        'ITP_LIMITATION_Lmax_TRAILED_VEHICLE' => 'Lungime maximă vehicul tractat Lmax=@param',
    ];

    public const ITP_INTERDICTIONS = [
        'ITP_INTERDICTION_TRACTORS' => 'Tractoare',
        'ITP_INTERDICTION_AUTO_PERMANENT_ALLWHEEL' => 'Autovehicule echipate cu tracțiune integrală permanentă',
        'ITP_INTERDICTION_AUTO_GPL' => 'Autovehicule echipate cu instalație GPL',
        'ITP_INTERDICTION_AUTO_WITHOUT_BRAKE_BOOSTER' => 'Autovehicule care nu sunt echipate cu dispozitiv de amplificare a efortului de apăsare la pedala de frână',
        'ITP_INTERDICTION_AUTO_MAC' => 'Autovehicule echipate cu MAC',
        'ITP_INTERDICTION_AUTO_MAS' => 'Autovehicule echipate cu MAS',
        'ITP_INTERDICTION_AUTO_MASKAT' => 'Autovehicule echipate cu MASKAT',
        'ITP_INTERDICTION_AUTO_PNEUMATIC_BRAKING_SYSTEM' => 'Autovehicule echipate cu sistem de frânare pneumatic fabricate după anul 2001 inclusiv',
        'ITP_INTERDICTION_TRAILERS' => 'Remorci cu sistem de frânare inerțial',
        'ITP_INTERDICTION_TOWED_VEHICLES' => 'Vehicule tractate',
        'ITP_INTERDICTION_VEHICLES_AMP_2150' => 'Vehicule care au ampatament între oricare 2 axe alăturate de 2150±250mm',
        'ITP_INTERDICTION_VEHICLES_MORE_4_AXLES' => 'Vehicule cu mai mult de 4 punți',
        'ITP_INTERDICTION_TRACKTORS_12' => 'Tractoare echipate cu anvelope de dimensiuni mai mari de 12.40-28\'\'',
        'ITP_INTERDICTION_AUTO_PERMANENT_ALLWHEEL_MORE_2_AXLES' => 'Autovehicule echipate cu tracțiune integrală permanentă cu mai mult de 2 axe',
        'ITP_INTERDICTION_SEMI_TRAILERS' => 'Semiremorci',
        'ITP_INTERDICTION_TRAILERS_DOUBLE_AXLES' => 'Remorci cu sistem de frânare inerțial cu 2 axe (punte dublă)',
        'ITP_INTERDICTION_VEHICLES_ADJACENT_AXLES' => 'Vehicule cu 2 sau mai multe punți alăturate',
        'ITP_INTERDICTION_VEHICLES_MULTI_AXLES' => 'Vehicule echipate cu punte dublă sau triplă',
        'ITP_INTERDICTION_AUTO_TWIN_WHEELS' => 'Autovehicule echipate cu roți jumelate',
        'ITP_INTERDICTION_AUTO_PERMANENT_ALLWHEEL_TWIN_WHEELS' => 'Autovehicule echipate tracțiune integrală permanentă și cu roți jumelate',
        'ITP_INTERDICTION_AUTO_GNC' => 'Autovehicule echipate cu instalație GNC',
        'ITP_INTERDICTION_AUTO_GPL_GNC' => 'Autovehicule echipate cu instalație GPL sau GNC',
        'ITP_INTERDICTION_ARTICULATED_BUSES' => 'Autobuze articulate',
        'ITP_INTERDICTION_AUTO_N2_N3' => 'Autovehicule din categoria N2 (cu excepția celor MTMA sub 7,5 To la care nu este posibilă montarea corespunzătoare a unei oglinzi de cls. V) și N3 fabricate după 01.01.2000 la care nu se prezintă Certificatul de Conformitate care atestă îndeplinirea prevederilor Dir. 2003-97-CE ref. la câmpul de vizibilitate sau nu există marcă de omologare pe suportul oglinzilor (conf. RNTR-1 Anexa 3)',
        'ITP_INTERDICTION_MOPEDS_MOTORCYCLES' => 'Mopede cu 2 roți, motociclete fără ataș',
        'ITP_INTERDICTION_VEHICLES_PNEUMATIC_BRAKING_SYSTEM' => 'Vehicule echipate cu sistem de frânare pneumatic',
        'ITP_INTERDICTION_AUTO_N2_N3_T' => 'Autovehicule din categoriile N2, N3 și T',
        'ITP_INTERDICTION_AUTO_EURO6' => 'Autovehicule cu norma de poluare EURO 6 sau EURO VI',
        'ITP_INTERDICTION_AUTO_M1_N1_2021' => 'Autovehicule din categoriile M1 și N1 înmatriculate prima dată începând cu anul 2021 și care la punctul V.9 din CIV au consemnat indicativele AP, AQ sau AR',
    ];

    public const ITP_OBSERVATIONS = [
        'ITP_OBSERVATIONS_1' => 'Nu se efectuează verificări ale eficacității sistemului de frânare al vehiculelor prin probe funcționale în parcurs',
        'ITP_OBSERVATIONS_2' => 'Nu se efectuează verificări ale eficacității sistemului de frânare al autovehiculelor prin probe funcționale în parcurs',
        'ITP_OBSERVATIONS_3' => 'Nu se efectuează verificări ale eficacității sistemului de frânare al autovehiculelor care nu sunt echipate cu dispozitiv de amplificare a efortului de apăsare la pedala de frână, prin probe funcționale în parcurs',
        'ITP_OBSERVATIONS_4' => 'Nu se efectuează verificări ale eficacității sistemului de frânare al vehiculelor tractate prin probe funcționale în parcurs',
        'ITP_OBSERVATIONS_5' => 'Nu se efectuează verificări ale eficacității sistemului de frânare la mopede cu 3 roți, motociclete cu ataș, mototricicluri și cvadricicluri prin probe funcționale în parcurs',
        'ITP_OBSERVATIONS_6' => 'Se efectuează verificări ale eficacității sistemului de frânare prin probe funcționale în parcurs numai la tractoare',
        'ITP_OBSERVATIONS_7' => 'Nu se efectuează verificări ale eficacității sistemului de frânare prin probe funcționale în parcurs la vehicule din clasa I, cu excepția celor din L7e, cu sistem de direcție acționat prin volan',
        'ITP_OBSERVATIONS_8' => 'Se efectuează ITP la autobuze articulate doar pentru parcul propriu',
        'ITP_OBSERVATIONS_ONLY_MAL' => 'Se permite efectuarea ITP doar pentru M.A.L.',
    ];
}
