<div>
    <div class="mb-6 flex justify-between"><div><h1 class="text-2xl font-bold">Filtre și atribute</h1><p class="text-stone-500">Definiții reutilizabile, opțiuni și reguli per categorie.</p></div><button wire:click="resetForm" class="rounded-lg bg-stone-950 px-4 py-2 text-sm font-semibold text-white">Filtru nou</button></div>
    @if(session('success'))<div class="mb-4 rounded-lg bg-lime-100 p-3 text-sm">{{ session('success') }}</div>@endif
    <form wire:submit="save" class="mb-6 grid gap-4 rounded-xl border bg-white p-5 lg:grid-cols-3">
        <div><label class="text-sm font-medium">Nume</label><input wire:model.live.debounce.400ms="name" class="mt-1 w-full rounded-lg border px-3 py-2">@error('name')<p class="text-xs text-red-600">{{ $message }}</p>@enderror</div>
        <div><label class="text-sm font-medium">Cod intern</label><input wire:model="code" class="mt-1 w-full rounded-lg border px-3 py-2">@error('code')<p class="text-xs text-red-600">{{ $message }}</p>@enderror</div>
        <div><label class="text-sm font-medium">Tip</label><select wire:model.live="type" class="mt-1 w-full rounded-lg border px-3 py-2">@foreach(['text','number','boolean','select','multiselect','color'] as $item)<option value="{{ $item }}">{{ $item }}</option>@endforeach</select></div>
        <div><label class="text-sm font-medium">Unitate</label><input wire:model="unit" placeholder="mm, kg, inch..." class="mt-1 w-full rounded-lg border px-3 py-2"></div>
        <div class="lg:col-span-2"><label class="text-sm font-medium">Ajutor pentru administrator/client</label><input wire:model="helpText" class="mt-1 w-full rounded-lg border px-3 py-2"></div>
        @if(in_array($type, ['select','multiselect','color']))<div class="lg:col-span-3"><label class="text-sm font-medium">Opțiuni (câte una pe linie: Etichetă|valoare)</label><textarea wire:model="optionsText" rows="5" class="mt-1 w-full rounded-lg border px-3 py-2 font-mono text-sm"></textarea></div>@endif
        <div class="lg:col-span-3"><label class="text-sm font-medium">Categorii</label><select wire:model="categoryIds" multiple size="8" class="mt-1 w-full rounded-lg border px-3 py-2">@foreach($categories as $category)<option value="{{ $category->id }}">{{ str_repeat('— ', $category->depth) }}{{ $category->name }}</option>@endforeach</select></div>
        <div class="flex flex-wrap gap-5 text-sm lg:col-span-3"><label><input type="checkbox" wire:model="isActive"> Activ</label><label><input type="checkbox" wire:model="isGlobal"> Global</label><label><input type="checkbox" wire:model="isFilterable"> Filtrabil</label><label><input type="checkbox" wire:model="isComparable"> Comparabil</label><label><input type="checkbox" wire:model="isRequired"> Obligatoriu</label><label><input type="checkbox" wire:model="isVariantDefining"> Definește varianta</label></div>
        <div class="flex gap-2 lg:col-span-3"><button class="rounded-lg bg-lime-400 px-5 py-2 font-semibold">Salvează</button>@if($editingId)<button type="button" wire:click="delete({{ $editingId }})" wire:confirm="Ștergi atributul și opțiunile lui?" class="rounded-lg bg-red-50 px-4 py-2 text-red-700">Șterge</button>@endif</div>
    </form>
    <div class="overflow-hidden rounded-xl border bg-white"><table class="w-full text-left text-sm"><thead class="bg-stone-50 text-stone-500"><tr><th class="p-3">Atribut</th><th class="p-3">Cod</th><th class="p-3">Tip</th><th class="p-3">Unitate</th><th class="p-3">Categorii</th><th class="p-3">Opțiuni</th></tr></thead><tbody>
    @foreach($attributes as $attribute)<tr class="border-t"><td class="p-3"><button wire:click="edit({{ $attribute->id }})" class="font-medium hover:underline">{{ $attribute->name }}</button></td><td class="p-3 font-mono text-xs">{{ $attribute->code }}</td><td class="p-3">{{ $attribute->type }}</td><td class="p-3">{{ $attribute->unit ?? '—' }}</td><td class="p-3">{{ $attribute->categories_count }}</td><td class="p-3">{{ $attribute->options_count }}</td></tr>@endforeach
    </tbody></table></div>
</div>
