<div>
    <div class="mb-6 flex items-start justify-between"><div><h1 class="text-2xl font-bold">Categorii</h1><p class="text-stone-500">Arbore complet, imagini, conținut și SEO administrabile.</p></div><button wire:click="resetForm" class="rounded-lg bg-stone-950 px-4 py-2 text-sm font-semibold text-white">Categorie nouă</button></div>
    @if(session('success'))<div class="mb-4 rounded-lg bg-lime-100 p-3 text-sm text-lime-900">{{ session('success') }}</div>@endif
    <form wire:submit="save" class="mb-6 grid gap-4 rounded-xl border bg-white p-5 lg:grid-cols-2">
        <div><label class="text-sm font-medium">Nume</label><input wire:model.live.debounce.400ms="name" class="mt-1 w-full rounded-lg border px-3 py-2">@error('name')<p class="text-xs text-red-600">{{ $message }}</p>@enderror</div>
        <div><label class="text-sm font-medium">Slug</label><input wire:model="slug" class="mt-1 w-full rounded-lg border px-3 py-2">@error('slug')<p class="text-xs text-red-600">{{ $message }}</p>@enderror</div>
        <div><label class="text-sm font-medium">Părinte</label><select wire:model="parentId" class="mt-1 w-full rounded-lg border px-3 py-2"><option value="">Rădăcină</option>@foreach($parentOptions as $option)<option value="{{ $option->id }}">{{ str_repeat('— ', $option->depth) }}{{ $option->name }}</option>@endforeach</select></div>
        <div><label class="text-sm font-medium">Imagine</label><input type="file" wire:model="image" accept="image/*" class="mt-1 w-full rounded-lg border px-3 py-2">@if($currentImage)<p class="mt-1 text-xs text-stone-500">Curentă: {{ $currentImage }}</p>@endif</div>
        <div class="lg:col-span-2"><label class="text-sm font-medium">Descriere</label><textarea wire:model="description" rows="4" class="mt-1 w-full rounded-lg border px-3 py-2"></textarea></div>
        <div><label class="text-sm font-medium">Titlu SEO</label><input wire:model="seoTitle" maxlength="255" class="mt-1 w-full rounded-lg border px-3 py-2"></div>
        <div><label class="text-sm font-medium">Descriere SEO</label><textarea wire:model="seoDescription" maxlength="320" rows="2" class="mt-1 w-full rounded-lg border px-3 py-2"></textarea></div>
        <div class="lg:col-span-2"><label class="text-sm font-medium">URL canonical</label><input wire:model="canonicalUrl" type="url" class="mt-1 w-full rounded-lg border px-3 py-2"></div>
        <div class="flex flex-wrap gap-5 text-sm lg:col-span-2"><label><input type="checkbox" wire:model="isActive"> Activă</label><label><input type="checkbox" wire:model="isVisibleInMenu"> În meniu</label><label><input type="checkbox" wire:model="robotsIndex"> Indexare SEO</label><label><input type="checkbox" wire:model="robotsFollow"> Follow linkuri</label></div>
        <div class="flex gap-2 lg:col-span-2"><button class="rounded-lg bg-lime-400 px-5 py-2 font-semibold">{{ $editingId ? 'Salvează modificările' : 'Adaugă categoria' }}</button>@if($editingId)<button type="button" wire:click="delete({{ $editingId }})" wire:confirm="Ștergi categoria?" class="rounded-lg bg-red-50 px-4 py-2 text-red-700">Șterge</button>@endif</div>
    </form>
    <input wire:model.live.debounce.300ms="search" placeholder="Caută o categorie" class="mb-4 w-full max-w-md rounded-lg border bg-white px-3 py-2">
    <div class="overflow-hidden rounded-xl border bg-white"><table class="w-full text-left text-sm"><thead class="bg-stone-50 text-stone-500"><tr><th class="p-3">Categorie</th><th class="p-3">Produse</th><th class="p-3">Filtre</th><th class="p-3">Activă</th></tr></thead><tbody>
    @foreach($categories as $category)<tr class="border-t"><td class="p-3"><span class="text-stone-300">{{ str_repeat('— ', $category->depth) }}</span><button wire:click="edit({{ $category->id }})" class="font-medium hover:underline">{{ $category->name }}</button><div class="ml-4 text-xs text-stone-400">{{ $category->full_path }}</div></td><td class="p-3">{{ $category->products_count }}</td><td class="p-3">{{ $category->attributes_count }}</td><td class="p-3"><div class="flex items-center gap-2"><button wire:click="toggle({{ $category->id }})" @class(['rounded-full px-3 py-1 text-xs font-semibold','bg-lime-100 text-lime-800'=>$category->is_active,'bg-stone-200 text-stone-600'=>!$category->is_active])>{{ $category->is_active ? 'Da' : 'Nu' }}</button><button wire:click="move({{ $category->id }}, 'up')" title="Mai sus">↑</button><button wire:click="move({{ $category->id }}, 'down')" title="Mai jos">↓</button></div></td></tr>@endforeach
    </tbody></table></div>
</div>
