<div x-data="{ tab: 'general' }">
    <div class="mb-6 flex items-start justify-between"><div><h1 class="text-2xl font-bold">{{ $product ? 'Editează produsul' : 'Produs nou' }}</h1><p class="text-stone-500">Catalog, variante, filtre, media, compatibilitate și SEO.</p></div><a href="{{ route('admin.products.index') }}" class="text-sm text-stone-600">← Înapoi</a></div>
    @if(session('success'))<div class="mb-4 rounded-lg bg-lime-100 p-3 text-sm text-lime-900">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">Verifică toate câmpurile marcate. {{ $errors->first() }}</div>@endif
    <div class="mb-4 flex flex-wrap gap-2">@foreach(['general'=>'General','variants'=>'Variante & preț','attributes'=>'Filtre','media'=>'Imagini','fitments'=>'Compatibilitate','seo'=>'SEO'] as $key=>$label)<button type="button" @click="tab='{{ $key }}'" :class="tab==='{{ $key }}' ? 'bg-stone-950 text-white' : 'bg-white'" class="rounded-lg border px-4 py-2 text-sm font-medium">{{ $label }}</button>@endforeach</div>
    <form wire:submit="save" class="rounded-xl border bg-white p-5">
        <section x-show="tab==='general'" class="grid gap-4 lg:grid-cols-2">
            <div><label class="text-sm font-medium">Nume *</label><input wire:model.live.debounce.400ms="name" class="mt-1 w-full rounded-lg border px-3 py-2"></div><div><label class="text-sm font-medium">Slug *</label><input wire:model="slug" class="mt-1 w-full rounded-lg border px-3 py-2"></div>
            <div><label class="text-sm font-medium">SKU produs</label><input wire:model="sku" class="mt-1 w-full rounded-lg border px-3 py-2"></div><div><label class="text-sm font-medium">Cod producător</label><input wire:model="manufacturerPartNumber" class="mt-1 w-full rounded-lg border px-3 py-2"></div>
            <div><label class="text-sm font-medium">Brand</label><select wire:model="brandId" class="mt-1 w-full rounded-lg border px-3 py-2"><option value="">Fără brand</option>@foreach($brands as $brand)<option value="{{ $brand->id }}">{{ $brand->name }}</option>@endforeach</select></div><div><label class="text-sm font-medium">Status</label><select wire:model="status" class="mt-1 w-full rounded-lg border px-3 py-2">@foreach(['draft'=>'Draft','review'=>'De verificat','active'=>'Publicat','archived'=>'Arhivat'] as $key=>$label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></div>
            <div class="lg:col-span-2"><label class="text-sm font-medium">Categorii * (prima este principală)</label><select wire:model.live="categoryIds" multiple size="8" class="mt-1 w-full rounded-lg border px-3 py-2">@foreach($categories as $category)<option value="{{ $category->id }}">{{ str_repeat('— ', $category->depth) }}{{ $category->name }}</option>@endforeach</select></div>
            <div class="lg:col-span-2"><label class="text-sm font-medium">Descriere scurtă</label><textarea wire:model="shortDescription" rows="3" class="mt-1 w-full rounded-lg border px-3 py-2"></textarea></div><div class="lg:col-span-2"><label class="text-sm font-medium">Descriere completă (HTML permis)</label><textarea wire:model="description" rows="12" class="mt-1 w-full rounded-lg border px-3 py-2 font-mono text-sm"></textarea></div>
            <div><label class="text-sm font-medium">Garanție (luni)</label><input type="number" wire:model="warrantyMonths" class="mt-1 w-full rounded-lg border px-3 py-2"></div><div><label class="text-sm font-medium">Greutate (kg)</label><input type="number" step="0.001" wire:model="weightKg" class="mt-1 w-full rounded-lg border px-3 py-2"></div>
            <div class="flex gap-5 text-sm lg:col-span-2"><label><input type="checkbox" wire:model="isUniversal"> Produs universal</label><label><input type="checkbox" wire:model="isFeatured"> Recomandat</label></div>
        </section>
        <section x-show="tab==='variants'" x-cloak><div class="mb-3 flex justify-between"><h2 class="font-semibold">Variante comerciale</h2><button type="button" wire:click="addVariant" class="rounded bg-stone-900 px-3 py-1.5 text-sm text-white">+ Variantă</button></div>
            <div class="space-y-3">@foreach($variants as $index=>$variant)<div wire:key="variant-{{ $index }}" class="grid gap-3 rounded-lg border p-3 md:grid-cols-4"><input wire:model="variants.{{ $index }}.name" placeholder="Nume" class="rounded border px-3 py-2"><input wire:model="variants.{{ $index }}.sku" placeholder="SKU *" class="rounded border px-3 py-2"><input wire:model="variants.{{ $index }}.mpn" placeholder="Cod producător" class="rounded border px-3 py-2"><input wire:model="variants.{{ $index }}.barcode" placeholder="EAN/UPC" class="rounded border px-3 py-2"><input type="number" step="0.01" wire:model="variants.{{ $index }}.price" placeholder="Preț" class="rounded border px-3 py-2"><input type="number" step="0.01" wire:model="variants.{{ $index }}.compare_at_price" placeholder="Preț vechi" class="rounded border px-3 py-2"><input type="number" step="0.001" wire:model="variants.{{ $index }}.weight_kg" placeholder="kg" class="rounded border px-3 py-2"><div class="flex items-center justify-between"><label class="text-sm"><input type="checkbox" wire:model="variants.{{ $index }}.is_active"> Activă</label>@if(count($variants)>1)<button type="button" wire:click="removeVariant({{ $index }})" class="text-sm text-red-600">Elimină</button>@endif</div></div>@endforeach</div>
        </section>
        <section x-show="tab==='attributes'" x-cloak><h2 class="mb-3 font-semibold">Atribute disponibile pentru categoriile selectate</h2><div class="grid gap-4 md:grid-cols-2">@forelse($attributes as $attribute)<div><label class="text-sm font-medium">{{ $attribute->name }} @if($attribute->unit)({{ $attribute->unit }})@endif</label>@if(in_array($attribute->type,['select','color']))<select wire:model="attributeValues.{{ $attribute->id }}" class="mt-1 w-full rounded border px-3 py-2"><option value="">—</option>@foreach($attribute->options as $option)<option value="{{ $option->id }}">{{ $option->label }}</option>@endforeach</select>@elseif($attribute->type==='multiselect')<select multiple wire:model="attributeValues.{{ $attribute->id }}" class="mt-1 w-full rounded border px-3 py-2">@foreach($attribute->options as $option)<option value="{{ $option->id }}">{{ $option->label }}</option>@endforeach</select>@elseif($attribute->type==='boolean')<label class="mt-2 block text-sm"><input type="checkbox" wire:model="attributeValues.{{ $attribute->id }}"> Da</label>@else<input type="{{ $attribute->type==='number' ? 'number':'text' }}" wire:model="attributeValues.{{ $attribute->id }}" class="mt-1 w-full rounded border px-3 py-2">@endif@if($attribute->help_text)<p class="text-xs text-stone-500">{{ $attribute->help_text }}</p>@endif</div>@empty<p class="text-stone-500">Selectează cel puțin o categorie sau definește atribute globale.</p>@endforelse</div></section>
        <section x-show="tab==='media'" x-cloak><label class="font-semibold">Încarcă imagini</label><input type="file" multiple accept="image/*" wire:model="images" class="mt-2 block w-full rounded border p-3"><div class="mt-4 grid grid-cols-2 gap-3 md:grid-cols-5">@foreach($existingMedia as $media)<div class="rounded border p-2"><img src="{{ Storage::disk($media->disk)->url($media->path) }}" alt="{{ $media->alt_text }}" class="aspect-square w-full object-cover"><button type="button" wire:click="removeMedia({{ $media->id }})" class="mt-2 text-xs text-red-600">Elimină</button></div>@endforeach</div></section>
        <section x-show="tab==='fitments'" x-cloak><div class="mb-3 flex justify-between"><h2 class="font-semibold">Compatibilitate auto</h2><button type="button" wire:click="addFitment" class="rounded bg-stone-900 px-3 py-1.5 text-sm text-white">+ Compatibilitate</button></div>@foreach($fitments as $index=>$fitment)<div wire:key="fitment-{{ $index }}" class="mb-3 grid gap-3 rounded border p-3 md:grid-cols-5"><select wire:model="fitments.{{ $index }}.generation_id" class="rounded border px-2 py-2 md:col-span-2"><option value="">Alege generația</option>@foreach($generations as $generation)<option value="{{ $generation->id }}">{{ $generation->model->make->name }} {{ $generation->model->name }} · {{ $generation->name }} ({{ $generation->year_from }}–{{ $generation->year_to ?: 'prezent' }})</option>@endforeach</select><input type="number" wire:model="fitments.{{ $index }}.year_from" placeholder="An de la" class="rounded border px-2"><input type="number" wire:model="fitments.{{ $index }}.year_to" placeholder="An până la" class="rounded border px-2"><input wire:model="fitments.{{ $index }}.position" placeholder="Poziție" class="rounded border px-2"><textarea wire:model="fitments.{{ $index }}.notes" placeholder="Note montaj" class="rounded border px-2 md:col-span-3"></textarea><label class="text-sm"><input type="checkbox" wire:model="fitments.{{ $index }}.requires_modification"> Necesită modificări</label><button type="button" wire:click="removeFitment({{ $index }})" class="text-sm text-red-600">Elimină</button></div>@endforeach</section>
        <section x-show="tab==='seo'" x-cloak class="grid gap-4"><div><label class="text-sm font-medium">Titlu SEO</label><input wire:model="seoTitle" maxlength="255" class="mt-1 w-full rounded border px-3 py-2"></div><div><label class="text-sm font-medium">Descriere SEO</label><textarea wire:model="seoDescription" maxlength="320" class="mt-1 w-full rounded border px-3 py-2"></textarea></div><div><label class="text-sm font-medium">URL canonical</label><input type="url" wire:model="canonicalUrl" class="mt-1 w-full rounded border px-3 py-2"></div><div class="flex gap-5 text-sm"><label><input type="checkbox" wire:model="robotsIndex"> Index</label><label><input type="checkbox" wire:model="robotsFollow"> Follow</label></div></section>
        <div class="mt-6 flex justify-between border-t pt-4"><button class="rounded-lg bg-lime-400 px-6 py-2.5 font-bold">Salvează produsul</button>@if($product)<button type="button" wire:click="deleteProduct" wire:confirm="Arhivezi produsul?" class="rounded-lg bg-red-50 px-4 py-2 text-red-700">Arhivează produsul</button>@endif</div>
    </form>
</div>
