<div>
    <div class="mb-6 flex items-start justify-between"><div><h1 class="text-2xl font-bold">Produse</h1><p class="text-stone-500">Catalogul canonic, separat de ofertele furnizorilor.</p></div><a href="{{ route('admin.products.create') }}" class="rounded-lg bg-stone-950 px-4 py-2 text-sm font-semibold text-white">Produs nou</a></div>
    <div class="mb-4 grid gap-3 rounded-xl border bg-white p-4 md:grid-cols-3">
        <input wire:model.live.debounce.300ms="search" placeholder="Nume, SKU sau cod producător" class="rounded-lg border px-3 py-2">
        <select wire:model.live="status" class="rounded-lg border px-3 py-2"><option value="">Toate statusurile</option>@foreach(['draft','review','active','archived'] as $item)<option>{{ $item }}</option>@endforeach</select>
        <select wire:model.live="category" class="rounded-lg border px-3 py-2"><option value="">Toate categoriile</option>@foreach($categories as $item)<option value="{{ $item->id }}">{{ str_repeat('— ', $item->depth) }}{{ $item->name }}</option>@endforeach</select>
    </div>
    <div class="overflow-hidden rounded-xl border bg-white"><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-stone-50 text-stone-500"><tr><th class="p-3">Produs</th><th class="p-3">Brand</th><th class="p-3">Variante</th><th class="p-3">Oferte</th><th class="p-3">Status</th></tr></thead><tbody>
    @forelse($products as $product)<tr class="border-t"><td class="p-3"><a href="{{ route('admin.products.edit', $product) }}" class="font-semibold hover:underline">{{ $product->name }}</a><div class="text-xs text-stone-500">{{ $product->sku ?: $product->manufacturer_part_number ?: 'fără cod' }}</div></td><td class="p-3">{{ $product->brand?->name ?? '—' }}</td><td class="p-3">{{ $product->variants->count() }}</td><td class="p-3">{{ $product->supplier_products_count }}</td><td class="p-3"><select wire:change="setStatus({{ $product->id }}, $event.target.value)" class="rounded border px-2 py-1"><option selected>{{ $product->status->value }}</option>@foreach(['draft','review','active','archived'] as $status) @if($status !== $product->status->value)<option>{{ $status }}</option>@endif @endforeach</select></td></tr>@empty<tr><td colspan="5" class="p-8 text-center text-stone-500">Nu există produse pentru filtrele alese.</td></tr>@endforelse
    </tbody></table></div><div class="border-t p-4">{{ $products->links() }}</div></div>
</div>
